// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/formancehq/fctl/v3/internal/membershipclient/models/components"
)

type Error struct {
	ErrorCode    string                  `json:"errorCode"`
	ErrorMessage *string                 `json:"errorMessage,omitzero"`
	HTTPMeta     components.HTTPMetadata `json:"-"`
}

var _ error = &Error{}

func (e *Error) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
