# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
project_name: fctl

includes:
  - from_url:
      url: https://raw.githubusercontent.com/formancehq/earthly/refs/heads/main/.goreleaser.default.yaml

builds:
  - binary: fctl
    id: fctl
    ldflags:
      - -X github.com/formancehq/fctl/v3/cmd/version.BuildDate={{ .Date }}
      - -X github.com/formancehq/fctl/v3/cmd/version.Version=v{{ .Version }}
      - -X github.com/formancehq/fctl/v3/cmd/version.Commit={{ .ShortCommit }}
      - -s
      - -w
      - -extldflags "-static"
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: "{{.ProjectName}}"
    builds:
      - fctl
    format_overrides:
      - goos: windows
        format: zip
    format: tar.gz
    name_template: "{{.ProjectName}}_{{.Os}}-{{.Arch}}"
    files:
    - completions/*

brews:
  - name: fctl
    alternative_names:
      - fctl@{{ .Major }}
    repository:
      owner: formancehq
      name: homebrew-tap
      pull_request:
        enabled: true
        base:
          owner: formancehq
          name: homebrew-tap
          branch: main
    directory: Formula
    homepage: https://formance.com
    skip_upload: 'false'
    test: |
      system "#{bin}/fctl version"
    install: |
      bin.install "fctl"
      bash_completion.install "completions/fctl.bash" => "fctl"
      zsh_completion.install "completions/fctl.zsh" => "_fctl"
      fish_completion.install "completions/fctl.fish"

nfpms:
  - id: packages
    package_name: fctl
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - fctl
    homepage: https://formance.com
    maintainer: Maxence Maireaux <maxence@formance.com>
    formats:
      - deb
      - rpm

furies:
  - account: formance
    ids:
      - packages

release:
  prerelease: auto
  footer: |
    ## What to do next?
    - Read the [documentation](https://docs.formance.com/)
    - Join our [GitHub Discussions](https://github.com/orgs/formancehq/discussions)
