# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
project_name: fctl

includes:
  - from_url:
      url: https://raw.githubusercontent.com/formancehq/earthly/refs/heads/main/.goreleaser.default-v2.yaml

builds:
  - binary: fctl
    id: fctl
    ldflags:
      - -X github.com/formancehq/fctl/v4/cmd/version.BuildDate={{ .Date }}
      - -X github.com/formancehq/fctl/v4/cmd/version.Version=v{{ .Version }}
      - -X github.com/formancehq/fctl/v4/cmd/version.Commit={{ .ShortCommit }}
      - -s
      - -w
      - -extldflags "-static"
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: "{{.ProjectName}}"
    ids:
      - fctl
    format_overrides:
      - goos: windows
        formats: [zip]
    formats: [tar.gz]
    name_template: "{{.ProjectName}}_{{.Os}}-{{.Arch}}"
    files:
    - completions/*

homebrew_casks:
  - name: fctl
    alternative_names:
      - fctl@{{ .Major }}
    binaries:
      - fctl
    completions:
      bash: completions/fctl.bash
      zsh: completions/fctl.zsh
      fish: completions/fctl.fish
    url:
      template: https://brew.formance.com/{{ .Tag }}/{{ .ArtifactName }}
    repository:
      owner: formancehq
      name: homebrew-tap
      pull_request:
        enabled: true
        base:
          owner: formancehq
          name: homebrew-tap
          branch: main
    directory: Casks
    homepage: https://formance.com
    description: Formance Control CLI
    skip_upload: 'false'
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fctl"]
          end

nfpms:
  - id: packages
    package_name: fctl
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    ids:
      - fctl
    homepage: https://formance.com
    maintainer: Maxence Maireaux <maxence@formance.com>
    formats:
      - deb
      - rpm

gemfury:
  - account: formance
    ids:
      - packages

release:
  prerelease: auto
  footer: |
    ## What to do next?
    - Read the [documentation](https://docs.formance.com/)
    - Join our [GitHub Discussions](https://github.com/orgs/formancehq/discussions)
