project_name: fctl
env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
before:
  hooks:
    - go mod download

builds:
  - binary: fctl
    id: fctl_windows
    ldflags:
      - -X github.com/numary/fctl/cmd.BuildDate={{ .Date }}
      - -X github.com/numary/fctl/cmd.Version={{ .Version }}
      - -X github.com/numary/fctl/cmd.Commit={{ .ShortCommit }}
    env:
      - CGO_ENABLED=0
      - CC=x86_64-w64-mingw32-gcc
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -tags=json1
  - binary: fctl
    id: fctl_linux_amd64
    ldflags:
      - -X github.com/numary/fctl/cmd.BuildDate={{ .Date }}
      - -X github.com/numary/fctl/cmd.Version={{ .Version }}
      - -X github.com/numary/fctl/cmd.Commit={{ .ShortCommit }}
      - -extldflags "-static"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=json1,netgo
  - binary: fctl
    id: fctl_linux_arm64
    ldflags:
      - -X github.com/numary/fctl/cmd.BuildDate={{ .Date }}
      - -X github.com/numary/fctl/cmd.Version={{ .Version }}
      - -X github.com/numary/fctl/cmd.Commit={{ .ShortCommit }}
      - -extldflags "-static"
    env:
      - CGO_ENABLED=0
      - CC=aarch64-linux-gnu-gcc
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -tags=json1,netgo
  - binary: fctl
    id: fctl_darwin
    ldflags:
      - -X github.com/numary/fctl/cmd.BuildDate={{ .Date }}
      - -X github.com/numary/fctl/cmd.Version={{ .Version }}
      - -X github.com/numary/fctl/cmd.Commit={{ .ShortCommit }}
      - -s
    env:
      - CGO_ENABLED=0
      - CC=/home/runner/work/osxcross/target/bin/o64-clang
      - CXX=/home/runner/work/osxcross/target/bin/o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -tags=json1

archives:
  - id: "fctl"
    builds:
      - fctl_linux_amd64
      - fctl_linux_arm64
      - fctl_darwin
      - fctl_windows
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows


checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^spec:'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999

release:
  prerelease: auto
