/*
Membership API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package membershipclient

import (
	"encoding/json"
	"fmt"
)

// checks if the PrivateRegionSecret type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrivateRegionSecret{}

// PrivateRegionSecret struct for PrivateRegionSecret
type PrivateRegionSecret struct {
	LastDigits string `json:"lastDigits"`
	Clear *string `json:"clear,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PrivateRegionSecret PrivateRegionSecret

// NewPrivateRegionSecret instantiates a new PrivateRegionSecret object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrivateRegionSecret(lastDigits string) *PrivateRegionSecret {
	this := PrivateRegionSecret{}
	this.LastDigits = lastDigits
	return &this
}

// NewPrivateRegionSecretWithDefaults instantiates a new PrivateRegionSecret object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrivateRegionSecretWithDefaults() *PrivateRegionSecret {
	this := PrivateRegionSecret{}
	return &this
}

// GetLastDigits returns the LastDigits field value
func (o *PrivateRegionSecret) GetLastDigits() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastDigits
}

// GetLastDigitsOk returns a tuple with the LastDigits field value
// and a boolean to check if the value has been set.
func (o *PrivateRegionSecret) GetLastDigitsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastDigits, true
}

// SetLastDigits sets field value
func (o *PrivateRegionSecret) SetLastDigits(v string) {
	o.LastDigits = v
}

// GetClear returns the Clear field value if set, zero value otherwise.
func (o *PrivateRegionSecret) GetClear() string {
	if o == nil || IsNil(o.Clear) {
		var ret string
		return ret
	}
	return *o.Clear
}

// GetClearOk returns a tuple with the Clear field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrivateRegionSecret) GetClearOk() (*string, bool) {
	if o == nil || IsNil(o.Clear) {
		return nil, false
	}
	return o.Clear, true
}

// HasClear returns a boolean if a field has been set.
func (o *PrivateRegionSecret) HasClear() bool {
	if o != nil && !IsNil(o.Clear) {
		return true
	}

	return false
}

// SetClear gets a reference to the given string and assigns it to the Clear field.
func (o *PrivateRegionSecret) SetClear(v string) {
	o.Clear = &v
}

func (o PrivateRegionSecret) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrivateRegionSecret) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["lastDigits"] = o.LastDigits
	if !IsNil(o.Clear) {
		toSerialize["clear"] = o.Clear
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PrivateRegionSecret) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"lastDigits",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPrivateRegionSecret := _PrivateRegionSecret{}

	err = json.Unmarshal(data, &varPrivateRegionSecret)

	if err != nil {
		return err
	}

	*o = PrivateRegionSecret(varPrivateRegionSecret)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "lastDigits")
		delete(additionalProperties, "clear")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePrivateRegionSecret struct {
	value *PrivateRegionSecret
	isSet bool
}

func (v NullablePrivateRegionSecret) Get() *PrivateRegionSecret {
	return v.value
}

func (v *NullablePrivateRegionSecret) Set(val *PrivateRegionSecret) {
	v.value = val
	v.isSet = true
}

func (v NullablePrivateRegionSecret) IsSet() bool {
	return v.isSet
}

func (v *NullablePrivateRegionSecret) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrivateRegionSecret(val *PrivateRegionSecret) *NullablePrivateRegionSecret {
	return &NullablePrivateRegionSecret{value: val, isSet: true}
}

func (v NullablePrivateRegionSecret) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrivateRegionSecret) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


