/*
Membership API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package membershipclient

import (
	"encoding/json"
)

// checks if the ListApplicationsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListApplicationsResponse{}

// ListApplicationsResponse struct for ListApplicationsResponse
type ListApplicationsResponse struct {
	Cursor *ListApplicationsResponseCursor `json:"cursor,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListApplicationsResponse ListApplicationsResponse

// NewListApplicationsResponse instantiates a new ListApplicationsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListApplicationsResponse() *ListApplicationsResponse {
	this := ListApplicationsResponse{}
	return &this
}

// NewListApplicationsResponseWithDefaults instantiates a new ListApplicationsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListApplicationsResponseWithDefaults() *ListApplicationsResponse {
	this := ListApplicationsResponse{}
	return &this
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *ListApplicationsResponse) GetCursor() ListApplicationsResponseCursor {
	if o == nil || IsNil(o.Cursor) {
		var ret ListApplicationsResponseCursor
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListApplicationsResponse) GetCursorOk() (*ListApplicationsResponseCursor, bool) {
	if o == nil || IsNil(o.Cursor) {
		return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *ListApplicationsResponse) HasCursor() bool {
	if o != nil && !IsNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given ListApplicationsResponseCursor and assigns it to the Cursor field.
func (o *ListApplicationsResponse) SetCursor(v ListApplicationsResponseCursor) {
	o.Cursor = &v
}

func (o ListApplicationsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListApplicationsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListApplicationsResponse) UnmarshalJSON(data []byte) (err error) {
	varListApplicationsResponse := _ListApplicationsResponse{}

	err = json.Unmarshal(data, &varListApplicationsResponse)

	if err != nil {
		return err
	}

	*o = ListApplicationsResponse(varListApplicationsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "cursor")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListApplicationsResponse struct {
	value *ListApplicationsResponse
	isSet bool
}

func (v NullableListApplicationsResponse) Get() *ListApplicationsResponse {
	return v.value
}

func (v *NullableListApplicationsResponse) Set(val *ListApplicationsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListApplicationsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListApplicationsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListApplicationsResponse(val *ListApplicationsResponse) *NullableListApplicationsResponse {
	return &NullableListApplicationsResponse{value: val, isSet: true}
}

func (v NullableListApplicationsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListApplicationsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


