/*
Membership API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package membershipclient

import (
	"encoding/json"
	"fmt"
)

// checks if the GetRegionVersionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRegionVersionsResponse{}

// GetRegionVersionsResponse struct for GetRegionVersionsResponse
type GetRegionVersionsResponse struct {
	Data []Version `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _GetRegionVersionsResponse GetRegionVersionsResponse

// NewGetRegionVersionsResponse instantiates a new GetRegionVersionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRegionVersionsResponse(data []Version) *GetRegionVersionsResponse {
	this := GetRegionVersionsResponse{}
	this.Data = data
	return &this
}

// NewGetRegionVersionsResponseWithDefaults instantiates a new GetRegionVersionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRegionVersionsResponseWithDefaults() *GetRegionVersionsResponse {
	this := GetRegionVersionsResponse{}
	return &this
}

// GetData returns the Data field value
func (o *GetRegionVersionsResponse) GetData() []Version {
	if o == nil {
		var ret []Version
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetRegionVersionsResponse) GetDataOk() ([]Version, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetRegionVersionsResponse) SetData(v []Version) {
	o.Data = v
}

func (o GetRegionVersionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRegionVersionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetRegionVersionsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetRegionVersionsResponse := _GetRegionVersionsResponse{}

	err = json.Unmarshal(data, &varGetRegionVersionsResponse)

	if err != nil {
		return err
	}

	*o = GetRegionVersionsResponse(varGetRegionVersionsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetRegionVersionsResponse struct {
	value *GetRegionVersionsResponse
	isSet bool
}

func (v NullableGetRegionVersionsResponse) Get() *GetRegionVersionsResponse {
	return v.value
}

func (v *NullableGetRegionVersionsResponse) Set(val *GetRegionVersionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRegionVersionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRegionVersionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRegionVersionsResponse(val *GetRegionVersionsResponse) *NullableGetRegionVersionsResponse {
	return &NullableGetRegionVersionsResponse{value: val, isSet: true}
}

func (v NullableGetRegionVersionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRegionVersionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


