/*
Membership API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package membershipclient

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the CreateClientResponseResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateClientResponseResponseData{}

// CreateClientResponseResponseData struct for CreateClientResponseResponseData
type CreateClientResponseResponseData struct {
	// Organization ID
	Id string `json:"id"`
	Secret OrganizationClientSecret `json:"secret"`
	// Name of the client
	Name string `json:"name"`
	// Description of the client
	Description string `json:"description"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	// The ID of the owner of the client (DEPRECATED will be empty)
	OwnerId string `json:"ownerId"`
	AdditionalProperties map[string]interface{}
}

type _CreateClientResponseResponseData CreateClientResponseResponseData

// NewCreateClientResponseResponseData instantiates a new CreateClientResponseResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateClientResponseResponseData(id string, secret OrganizationClientSecret, name string, description string, createdAt time.Time, updatedAt time.Time, ownerId string) *CreateClientResponseResponseData {
	this := CreateClientResponseResponseData{}
	this.Id = id
	this.Secret = secret
	this.Name = name
	this.Description = description
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.OwnerId = ownerId
	return &this
}

// NewCreateClientResponseResponseDataWithDefaults instantiates a new CreateClientResponseResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateClientResponseResponseDataWithDefaults() *CreateClientResponseResponseData {
	this := CreateClientResponseResponseData{}
	return &this
}

// GetId returns the Id field value
func (o *CreateClientResponseResponseData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateClientResponseResponseData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateClientResponseResponseData) SetId(v string) {
	o.Id = v
}

// GetSecret returns the Secret field value
func (o *CreateClientResponseResponseData) GetSecret() OrganizationClientSecret {
	if o == nil {
		var ret OrganizationClientSecret
		return ret
	}

	return o.Secret
}

// GetSecretOk returns a tuple with the Secret field value
// and a boolean to check if the value has been set.
func (o *CreateClientResponseResponseData) GetSecretOk() (*OrganizationClientSecret, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Secret, true
}

// SetSecret sets field value
func (o *CreateClientResponseResponseData) SetSecret(v OrganizationClientSecret) {
	o.Secret = v
}

// GetName returns the Name field value
func (o *CreateClientResponseResponseData) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateClientResponseResponseData) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateClientResponseResponseData) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *CreateClientResponseResponseData) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *CreateClientResponseResponseData) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *CreateClientResponseResponseData) SetDescription(v string) {
	o.Description = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *CreateClientResponseResponseData) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *CreateClientResponseResponseData) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *CreateClientResponseResponseData) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *CreateClientResponseResponseData) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *CreateClientResponseResponseData) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *CreateClientResponseResponseData) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetOwnerId returns the OwnerId field value
func (o *CreateClientResponseResponseData) GetOwnerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OwnerId
}

// GetOwnerIdOk returns a tuple with the OwnerId field value
// and a boolean to check if the value has been set.
func (o *CreateClientResponseResponseData) GetOwnerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OwnerId, true
}

// SetOwnerId sets field value
func (o *CreateClientResponseResponseData) SetOwnerId(v string) {
	o.OwnerId = v
}

func (o CreateClientResponseResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateClientResponseResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["secret"] = o.Secret
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	toSerialize["ownerId"] = o.OwnerId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateClientResponseResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"secret",
		"name",
		"description",
		"createdAt",
		"updatedAt",
		"ownerId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateClientResponseResponseData := _CreateClientResponseResponseData{}

	err = json.Unmarshal(data, &varCreateClientResponseResponseData)

	if err != nil {
		return err
	}

	*o = CreateClientResponseResponseData(varCreateClientResponseResponseData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "secret")
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		delete(additionalProperties, "ownerId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateClientResponseResponseData struct {
	value *CreateClientResponseResponseData
	isSet bool
}

func (v NullableCreateClientResponseResponseData) Get() *CreateClientResponseResponseData {
	return v.value
}

func (v *NullableCreateClientResponseResponseData) Set(val *CreateClientResponseResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateClientResponseResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateClientResponseResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateClientResponseResponseData(val *CreateClientResponseResponseData) *NullableCreateClientResponseResponseData {
	return &NullableCreateClientResponseResponseData{value: val, isSet: true}
}

func (v NullableCreateClientResponseResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateClientResponseResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


