/*
Membership API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package membershipclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LogCursor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LogCursor{}

// LogCursor struct for LogCursor
type LogCursor struct {
	Data LogCursorData `json:"data"`
}

type _LogCursor LogCursor

// NewLogCursor instantiates a new LogCursor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLogCursor(data LogCursorData) *LogCursor {
	this := LogCursor{}
	this.Data = data
	return &this
}

// NewLogCursorWithDefaults instantiates a new LogCursor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLogCursorWithDefaults() *LogCursor {
	this := LogCursor{}
	return &this
}

// GetData returns the Data field value
func (o *LogCursor) GetData() LogCursorData {
	if o == nil {
		var ret LogCursorData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *LogCursor) GetDataOk() (*LogCursorData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *LogCursor) SetData(v LogCursorData) {
	o.Data = v
}

func (o LogCursor) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LogCursor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *LogCursor) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLogCursor := _LogCursor{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLogCursor)

	if err != nil {
		return err
	}

	*o = LogCursor(varLogCursor)

	return err
}

type NullableLogCursor struct {
	value *LogCursor
	isSet bool
}

func (v NullableLogCursor) Get() *LogCursor {
	return v.value
}

func (v *NullableLogCursor) Set(val *LogCursor) {
	v.value = val
	v.isSet = true
}

func (v NullableLogCursor) IsSet() bool {
	return v.isSet
}

func (v *NullableLogCursor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLogCursor(val *LogCursor) *NullableLogCursor {
	return &NullableLogCursor{value: val, isSet: true}
}

func (v NullableLogCursor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLogCursor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


