/*
Membership API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package membershipclient

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateClientResponseAllOfSecret type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateClientResponseAllOfSecret{}

// CreateClientResponseAllOfSecret struct for CreateClientResponseAllOfSecret
type CreateClientResponseAllOfSecret struct {
	LastDigits string `json:"lastDigits"`
	Clear *string `json:"clear,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateClientResponseAllOfSecret CreateClientResponseAllOfSecret

// NewCreateClientResponseAllOfSecret instantiates a new CreateClientResponseAllOfSecret object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateClientResponseAllOfSecret(lastDigits string) *CreateClientResponseAllOfSecret {
	this := CreateClientResponseAllOfSecret{}
	this.LastDigits = lastDigits
	return &this
}

// NewCreateClientResponseAllOfSecretWithDefaults instantiates a new CreateClientResponseAllOfSecret object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateClientResponseAllOfSecretWithDefaults() *CreateClientResponseAllOfSecret {
	this := CreateClientResponseAllOfSecret{}
	return &this
}

// GetLastDigits returns the LastDigits field value
func (o *CreateClientResponseAllOfSecret) GetLastDigits() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastDigits
}

// GetLastDigitsOk returns a tuple with the LastDigits field value
// and a boolean to check if the value has been set.
func (o *CreateClientResponseAllOfSecret) GetLastDigitsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastDigits, true
}

// SetLastDigits sets field value
func (o *CreateClientResponseAllOfSecret) SetLastDigits(v string) {
	o.LastDigits = v
}

// GetClear returns the Clear field value if set, zero value otherwise.
func (o *CreateClientResponseAllOfSecret) GetClear() string {
	if o == nil || IsNil(o.Clear) {
		var ret string
		return ret
	}
	return *o.Clear
}

// GetClearOk returns a tuple with the Clear field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClientResponseAllOfSecret) GetClearOk() (*string, bool) {
	if o == nil || IsNil(o.Clear) {
		return nil, false
	}
	return o.Clear, true
}

// HasClear returns a boolean if a field has been set.
func (o *CreateClientResponseAllOfSecret) HasClear() bool {
	if o != nil && !IsNil(o.Clear) {
		return true
	}

	return false
}

// SetClear gets a reference to the given string and assigns it to the Clear field.
func (o *CreateClientResponseAllOfSecret) SetClear(v string) {
	o.Clear = &v
}

func (o CreateClientResponseAllOfSecret) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateClientResponseAllOfSecret) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["lastDigits"] = o.LastDigits
	if !IsNil(o.Clear) {
		toSerialize["clear"] = o.Clear
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateClientResponseAllOfSecret) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"lastDigits",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateClientResponseAllOfSecret := _CreateClientResponseAllOfSecret{}

	err = json.Unmarshal(data, &varCreateClientResponseAllOfSecret)

	if err != nil {
		return err
	}

	*o = CreateClientResponseAllOfSecret(varCreateClientResponseAllOfSecret)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "lastDigits")
		delete(additionalProperties, "clear")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateClientResponseAllOfSecret struct {
	value *CreateClientResponseAllOfSecret
	isSet bool
}

func (v NullableCreateClientResponseAllOfSecret) Get() *CreateClientResponseAllOfSecret {
	return v.value
}

func (v *NullableCreateClientResponseAllOfSecret) Set(val *CreateClientResponseAllOfSecret) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateClientResponseAllOfSecret) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateClientResponseAllOfSecret) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateClientResponseAllOfSecret(val *CreateClientResponseAllOfSecret) *NullableCreateClientResponseAllOfSecret {
	return &NullableCreateClientResponseAllOfSecret{value: val, isSet: true}
}

func (v NullableCreateClientResponseAllOfSecret) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateClientResponseAllOfSecret) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


