/*
Membership API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package membershipclient

import (
	"encoding/json"
	"fmt"
)

// checks if the GetRegionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRegionResponse{}

// GetRegionResponse struct for GetRegionResponse
type GetRegionResponse struct {
	Data AnyRegion `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _GetRegionResponse GetRegionResponse

// NewGetRegionResponse instantiates a new GetRegionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRegionResponse(data AnyRegion) *GetRegionResponse {
	this := GetRegionResponse{}
	this.Data = data
	return &this
}

// NewGetRegionResponseWithDefaults instantiates a new GetRegionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRegionResponseWithDefaults() *GetRegionResponse {
	this := GetRegionResponse{}
	return &this
}

// GetData returns the Data field value
func (o *GetRegionResponse) GetData() AnyRegion {
	if o == nil {
		var ret AnyRegion
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetRegionResponse) GetDataOk() (*AnyRegion, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetRegionResponse) SetData(v AnyRegion) {
	o.Data = v
}

func (o GetRegionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRegionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetRegionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetRegionResponse := _GetRegionResponse{}

	err = json.Unmarshal(data, &varGetRegionResponse)

	if err != nil {
		return err
	}

	*o = GetRegionResponse(varGetRegionResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetRegionResponse struct {
	value *GetRegionResponse
	isSet bool
}

func (v NullableGetRegionResponse) Get() *GetRegionResponse {
	return v.value
}

func (v *NullableGetRegionResponse) Set(val *GetRegionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRegionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRegionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRegionResponse(val *GetRegionResponse) *NullableGetRegionResponse {
	return &NullableGetRegionResponse{value: val, isSet: true}
}

func (v NullableGetRegionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRegionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


