/*
Membership API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package membershipclient

import (
	"encoding/json"
	"fmt"
)

// checks if the ReadOrganizationClientResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReadOrganizationClientResponse{}

// ReadOrganizationClientResponse struct for ReadOrganizationClientResponse
type ReadOrganizationClientResponse struct {
	Data OrganizationClient `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _ReadOrganizationClientResponse ReadOrganizationClientResponse

// NewReadOrganizationClientResponse instantiates a new ReadOrganizationClientResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReadOrganizationClientResponse(data OrganizationClient) *ReadOrganizationClientResponse {
	this := ReadOrganizationClientResponse{}
	this.Data = data
	return &this
}

// NewReadOrganizationClientResponseWithDefaults instantiates a new ReadOrganizationClientResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReadOrganizationClientResponseWithDefaults() *ReadOrganizationClientResponse {
	this := ReadOrganizationClientResponse{}
	return &this
}

// GetData returns the Data field value
func (o *ReadOrganizationClientResponse) GetData() OrganizationClient {
	if o == nil {
		var ret OrganizationClient
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ReadOrganizationClientResponse) GetDataOk() (*OrganizationClient, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ReadOrganizationClientResponse) SetData(v OrganizationClient) {
	o.Data = v
}

func (o ReadOrganizationClientResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReadOrganizationClientResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReadOrganizationClientResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReadOrganizationClientResponse := _ReadOrganizationClientResponse{}

	err = json.Unmarshal(data, &varReadOrganizationClientResponse)

	if err != nil {
		return err
	}

	*o = ReadOrganizationClientResponse(varReadOrganizationClientResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReadOrganizationClientResponse struct {
	value *ReadOrganizationClientResponse
	isSet bool
}

func (v NullableReadOrganizationClientResponse) Get() *ReadOrganizationClientResponse {
	return v.value
}

func (v *NullableReadOrganizationClientResponse) Set(val *ReadOrganizationClientResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableReadOrganizationClientResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableReadOrganizationClientResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReadOrganizationClientResponse(val *ReadOrganizationClientResponse) *NullableReadOrganizationClientResponse {
	return &NullableReadOrganizationClientResponse{value: val, isSet: true}
}

func (v NullableReadOrganizationClientResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReadOrganizationClientResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


