/*
Membership API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package membershipclient

import (
	"encoding/json"
)

// checks if the CreateOrganizationClientRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrganizationClientRequest{}

// CreateOrganizationClientRequest struct for CreateOrganizationClientRequest
type CreateOrganizationClientRequest struct {
	// Description of the client
	Description *string `json:"description,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateOrganizationClientRequest CreateOrganizationClientRequest

// NewCreateOrganizationClientRequest instantiates a new CreateOrganizationClientRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrganizationClientRequest() *CreateOrganizationClientRequest {
	this := CreateOrganizationClientRequest{}
	return &this
}

// NewCreateOrganizationClientRequestWithDefaults instantiates a new CreateOrganizationClientRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrganizationClientRequestWithDefaults() *CreateOrganizationClientRequest {
	this := CreateOrganizationClientRequest{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateOrganizationClientRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrganizationClientRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateOrganizationClientRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateOrganizationClientRequest) SetDescription(v string) {
	o.Description = &v
}

func (o CreateOrganizationClientRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrganizationClientRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateOrganizationClientRequest) UnmarshalJSON(data []byte) (err error) {
	varCreateOrganizationClientRequest := _CreateOrganizationClientRequest{}

	err = json.Unmarshal(data, &varCreateOrganizationClientRequest)

	if err != nil {
		return err
	}

	*o = CreateOrganizationClientRequest(varCreateOrganizationClientRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "description")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateOrganizationClientRequest struct {
	value *CreateOrganizationClientRequest
	isSet bool
}

func (v NullableCreateOrganizationClientRequest) Get() *CreateOrganizationClientRequest {
	return v.value
}

func (v *NullableCreateOrganizationClientRequest) Set(val *CreateOrganizationClientRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrganizationClientRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrganizationClientRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrganizationClientRequest(val *CreateOrganizationClientRequest) *NullableCreateOrganizationClientRequest {
	return &NullableCreateOrganizationClientRequest{value: val, isSet: true}
}

func (v NullableCreateOrganizationClientRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrganizationClientRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


