/*
Membership API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package membershipclient

import (
	"encoding/json"
)

// checks if the CreateApplicationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateApplicationResponse{}

// CreateApplicationResponse struct for CreateApplicationResponse
type CreateApplicationResponse struct {
	Data *Application `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateApplicationResponse CreateApplicationResponse

// NewCreateApplicationResponse instantiates a new CreateApplicationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateApplicationResponse() *CreateApplicationResponse {
	this := CreateApplicationResponse{}
	return &this
}

// NewCreateApplicationResponseWithDefaults instantiates a new CreateApplicationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateApplicationResponseWithDefaults() *CreateApplicationResponse {
	this := CreateApplicationResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateApplicationResponse) GetData() Application {
	if o == nil || IsNil(o.Data) {
		var ret Application
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplicationResponse) GetDataOk() (*Application, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateApplicationResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given Application and assigns it to the Data field.
func (o *CreateApplicationResponse) SetData(v Application) {
	o.Data = &v
}

func (o CreateApplicationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateApplicationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateApplicationResponse) UnmarshalJSON(data []byte) (err error) {
	varCreateApplicationResponse := _CreateApplicationResponse{}

	err = json.Unmarshal(data, &varCreateApplicationResponse)

	if err != nil {
		return err
	}

	*o = CreateApplicationResponse(varCreateApplicationResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateApplicationResponse struct {
	value *CreateApplicationResponse
	isSet bool
}

func (v NullableCreateApplicationResponse) Get() *CreateApplicationResponse {
	return v.value
}

func (v *NullableCreateApplicationResponse) Set(val *CreateApplicationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateApplicationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateApplicationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateApplicationResponse(val *CreateApplicationResponse) *NullableCreateApplicationResponse {
	return &NullableCreateApplicationResponse{value: val, isSet: true}
}

func (v NullableCreateApplicationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateApplicationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


