/*
Membership API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package membershipclient

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the Organization type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Organization{}

// Organization struct for Organization
type Organization struct {
	// Organization name
	Name string `json:"name"`
	// Organization domain
	Domain *string `json:"domain,omitempty"`
	// Default policy ID applied to new users
	DefaultPolicyID NullableInt32 `json:"defaultPolicyID"`
	// Organization ID
	Id string `json:"id"`
	// Owner ID
	OwnerId string `json:"ownerId"`
	// Number of available stacks
	AvailableStacks *int32 `json:"availableStacks,omitempty"`
	// Number of available sandboxes
	AvailableSandboxes *int32 `json:"availableSandboxes,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Organization Organization

// NewOrganization instantiates a new Organization object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganization(name string, defaultPolicyID NullableInt32, id string, ownerId string) *Organization {
	this := Organization{}
	this.Name = name
	this.DefaultPolicyID = defaultPolicyID
	this.Id = id
	this.OwnerId = ownerId
	return &this
}

// NewOrganizationWithDefaults instantiates a new Organization object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationWithDefaults() *Organization {
	this := Organization{}
	return &this
}

// GetName returns the Name field value
func (o *Organization) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Organization) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Organization) SetName(v string) {
	o.Name = v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *Organization) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *Organization) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *Organization) SetDomain(v string) {
	o.Domain = &v
}

// GetDefaultPolicyID returns the DefaultPolicyID field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *Organization) GetDefaultPolicyID() int32 {
	if o == nil || o.DefaultPolicyID.Get() == nil {
		var ret int32
		return ret
	}

	return *o.DefaultPolicyID.Get()
}

// GetDefaultPolicyIDOk returns a tuple with the DefaultPolicyID field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Organization) GetDefaultPolicyIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultPolicyID.Get(), o.DefaultPolicyID.IsSet()
}

// SetDefaultPolicyID sets field value
func (o *Organization) SetDefaultPolicyID(v int32) {
	o.DefaultPolicyID.Set(&v)
}

// GetId returns the Id field value
func (o *Organization) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Organization) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Organization) SetId(v string) {
	o.Id = v
}

// GetOwnerId returns the OwnerId field value
func (o *Organization) GetOwnerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OwnerId
}

// GetOwnerIdOk returns a tuple with the OwnerId field value
// and a boolean to check if the value has been set.
func (o *Organization) GetOwnerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OwnerId, true
}

// SetOwnerId sets field value
func (o *Organization) SetOwnerId(v string) {
	o.OwnerId = v
}

// GetAvailableStacks returns the AvailableStacks field value if set, zero value otherwise.
func (o *Organization) GetAvailableStacks() int32 {
	if o == nil || IsNil(o.AvailableStacks) {
		var ret int32
		return ret
	}
	return *o.AvailableStacks
}

// GetAvailableStacksOk returns a tuple with the AvailableStacks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetAvailableStacksOk() (*int32, bool) {
	if o == nil || IsNil(o.AvailableStacks) {
		return nil, false
	}
	return o.AvailableStacks, true
}

// HasAvailableStacks returns a boolean if a field has been set.
func (o *Organization) HasAvailableStacks() bool {
	if o != nil && !IsNil(o.AvailableStacks) {
		return true
	}

	return false
}

// SetAvailableStacks gets a reference to the given int32 and assigns it to the AvailableStacks field.
func (o *Organization) SetAvailableStacks(v int32) {
	o.AvailableStacks = &v
}

// GetAvailableSandboxes returns the AvailableSandboxes field value if set, zero value otherwise.
func (o *Organization) GetAvailableSandboxes() int32 {
	if o == nil || IsNil(o.AvailableSandboxes) {
		var ret int32
		return ret
	}
	return *o.AvailableSandboxes
}

// GetAvailableSandboxesOk returns a tuple with the AvailableSandboxes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetAvailableSandboxesOk() (*int32, bool) {
	if o == nil || IsNil(o.AvailableSandboxes) {
		return nil, false
	}
	return o.AvailableSandboxes, true
}

// HasAvailableSandboxes returns a boolean if a field has been set.
func (o *Organization) HasAvailableSandboxes() bool {
	if o != nil && !IsNil(o.AvailableSandboxes) {
		return true
	}

	return false
}

// SetAvailableSandboxes gets a reference to the given int32 and assigns it to the AvailableSandboxes field.
func (o *Organization) SetAvailableSandboxes(v int32) {
	o.AvailableSandboxes = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Organization) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Organization) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Organization) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Organization) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organization) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Organization) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Organization) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o Organization) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Organization) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	toSerialize["defaultPolicyID"] = o.DefaultPolicyID.Get()
	toSerialize["id"] = o.Id
	toSerialize["ownerId"] = o.OwnerId
	if !IsNil(o.AvailableStacks) {
		toSerialize["availableStacks"] = o.AvailableStacks
	}
	if !IsNil(o.AvailableSandboxes) {
		toSerialize["availableSandboxes"] = o.AvailableSandboxes
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Organization) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"defaultPolicyID",
		"id",
		"ownerId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganization := _Organization{}

	err = json.Unmarshal(data, &varOrganization)

	if err != nil {
		return err
	}

	*o = Organization(varOrganization)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "domain")
		delete(additionalProperties, "defaultPolicyID")
		delete(additionalProperties, "id")
		delete(additionalProperties, "ownerId")
		delete(additionalProperties, "availableStacks")
		delete(additionalProperties, "availableSandboxes")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOrganization struct {
	value *Organization
	isSet bool
}

func (v NullableOrganization) Get() *Organization {
	return v.value
}

func (v *NullableOrganization) Set(val *Organization) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganization) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganization) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganization(val *Organization) *NullableOrganization {
	return &NullableOrganization{value: val, isSet: true}
}

func (v NullableOrganization) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganization) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


