/*
Membership API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package membershipclient

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the AuthenticationProviderResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthenticationProviderResponseData{}

// AuthenticationProviderResponseData struct for AuthenticationProviderResponseData
type AuthenticationProviderResponseData struct {
	// Type of the authentication provider
	Type string `json:"type"`
	// Name of the authentication provider
	Name string `json:"name"`
	// Client ID for the authentication provider
	ClientID string `json:"clientID"`
	// Client secret for the authentication provider
	ClientSecret string `json:"clientSecret"`
	Config OIDCConfigAllOfConfig `json:"config"`
	// Unique identifier for the authentication provider
	OrganizationId string `json:"organizationId"`
	// Creation date of the authentication provider
	CreatedAt time.Time `json:"createdAt"`
	// Last update date of the authentication provider
	UpdatedAt time.Time `json:"updatedAt"`
	RedirectURI string `json:"redirectURI"`
	AdditionalProperties map[string]interface{}
}

type _AuthenticationProviderResponseData AuthenticationProviderResponseData

// NewAuthenticationProviderResponseData instantiates a new AuthenticationProviderResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthenticationProviderResponseData(type_ string, name string, clientID string, clientSecret string, config OIDCConfigAllOfConfig, organizationId string, createdAt time.Time, updatedAt time.Time, redirectURI string) *AuthenticationProviderResponseData {
	this := AuthenticationProviderResponseData{}
	this.Type = type_
	this.Name = name
	this.ClientID = clientID
	this.ClientSecret = clientSecret
	this.Config = config
	this.OrganizationId = organizationId
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.RedirectURI = redirectURI
	return &this
}

// NewAuthenticationProviderResponseDataWithDefaults instantiates a new AuthenticationProviderResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthenticationProviderResponseDataWithDefaults() *AuthenticationProviderResponseData {
	this := AuthenticationProviderResponseData{}
	return &this
}

// GetType returns the Type field value
func (o *AuthenticationProviderResponseData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AuthenticationProviderResponseData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AuthenticationProviderResponseData) SetType(v string) {
	o.Type = v
}

// GetName returns the Name field value
func (o *AuthenticationProviderResponseData) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AuthenticationProviderResponseData) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AuthenticationProviderResponseData) SetName(v string) {
	o.Name = v
}

// GetClientID returns the ClientID field value
func (o *AuthenticationProviderResponseData) GetClientID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientID
}

// GetClientIDOk returns a tuple with the ClientID field value
// and a boolean to check if the value has been set.
func (o *AuthenticationProviderResponseData) GetClientIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientID, true
}

// SetClientID sets field value
func (o *AuthenticationProviderResponseData) SetClientID(v string) {
	o.ClientID = v
}

// GetClientSecret returns the ClientSecret field value
func (o *AuthenticationProviderResponseData) GetClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value
// and a boolean to check if the value has been set.
func (o *AuthenticationProviderResponseData) GetClientSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientSecret, true
}

// SetClientSecret sets field value
func (o *AuthenticationProviderResponseData) SetClientSecret(v string) {
	o.ClientSecret = v
}

// GetConfig returns the Config field value
func (o *AuthenticationProviderResponseData) GetConfig() OIDCConfigAllOfConfig {
	if o == nil {
		var ret OIDCConfigAllOfConfig
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *AuthenticationProviderResponseData) GetConfigOk() (*OIDCConfigAllOfConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Config, true
}

// SetConfig sets field value
func (o *AuthenticationProviderResponseData) SetConfig(v OIDCConfigAllOfConfig) {
	o.Config = v
}

// GetOrganizationId returns the OrganizationId field value
func (o *AuthenticationProviderResponseData) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *AuthenticationProviderResponseData) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *AuthenticationProviderResponseData) SetOrganizationId(v string) {
	o.OrganizationId = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *AuthenticationProviderResponseData) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AuthenticationProviderResponseData) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AuthenticationProviderResponseData) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *AuthenticationProviderResponseData) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *AuthenticationProviderResponseData) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *AuthenticationProviderResponseData) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetRedirectURI returns the RedirectURI field value
func (o *AuthenticationProviderResponseData) GetRedirectURI() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RedirectURI
}

// GetRedirectURIOk returns a tuple with the RedirectURI field value
// and a boolean to check if the value has been set.
func (o *AuthenticationProviderResponseData) GetRedirectURIOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RedirectURI, true
}

// SetRedirectURI sets field value
func (o *AuthenticationProviderResponseData) SetRedirectURI(v string) {
	o.RedirectURI = v
}

func (o AuthenticationProviderResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthenticationProviderResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["name"] = o.Name
	toSerialize["clientID"] = o.ClientID
	toSerialize["clientSecret"] = o.ClientSecret
	toSerialize["config"] = o.Config
	toSerialize["organizationId"] = o.OrganizationId
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	toSerialize["redirectURI"] = o.RedirectURI

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AuthenticationProviderResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"name",
		"clientID",
		"clientSecret",
		"config",
		"organizationId",
		"createdAt",
		"updatedAt",
		"redirectURI",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthenticationProviderResponseData := _AuthenticationProviderResponseData{}

	err = json.Unmarshal(data, &varAuthenticationProviderResponseData)

	if err != nil {
		return err
	}

	*o = AuthenticationProviderResponseData(varAuthenticationProviderResponseData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "name")
		delete(additionalProperties, "clientID")
		delete(additionalProperties, "clientSecret")
		delete(additionalProperties, "config")
		delete(additionalProperties, "organizationId")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		delete(additionalProperties, "redirectURI")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAuthenticationProviderResponseData struct {
	value *AuthenticationProviderResponseData
	isSet bool
}

func (v NullableAuthenticationProviderResponseData) Get() *AuthenticationProviderResponseData {
	return v.value
}

func (v *NullableAuthenticationProviderResponseData) Set(val *AuthenticationProviderResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthenticationProviderResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthenticationProviderResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthenticationProviderResponseData(val *AuthenticationProviderResponseData) *NullableAuthenticationProviderResponseData {
	return &NullableAuthenticationProviderResponseData{value: val, isSet: true}
}

func (v NullableAuthenticationProviderResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthenticationProviderResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


