// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3b7d438b6e4b

package operations

import (
	"github.com/formancehq/fctl/internal/deployserverclient/v3/models/components"
)

type DetachAppManifestRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DetachAppManifestRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DetachAppManifestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	Error *components.Error
}

func (d *DetachAppManifestResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DetachAppManifestResponse) GetError() *components.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
