// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: bc6fb185b576

package operations

import (
	"github.com/formancehq/fctl/internal/deployserverclient/v3/models/components"
)

type ListManifestsRequest struct {
	// Maximum number of items to return on the first page. Capped at 100;
	// ignored when `cursor` is supplied (subsequent pages reuse the page
	// size baked into the cursor token). Defaults to 100.
	//
	PageSize *int64 `queryParam:"style=form,explode=true,name=pageSize"`
	// Opaque pagination token returned in `cursor.next` / `cursor.previous`
	// on the previous page. Pass it back unchanged to fetch the adjacent
	// page. Mutually exclusive with `pageSize` after the first request.
	//
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
}

func (l *ListManifestsRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

func (l *ListManifestsRequest) GetCursor() *string {
	if l == nil {
		return nil
	}
	return l.Cursor
}

type ListManifestsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Manifests retrieved successfully
	ListManifestsResponse *components.ListManifestsResponse
	// Error
	Error *components.Error
}

func (l *ListManifestsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListManifestsResponse) GetListManifestsResponse() *components.ListManifestsResponse {
	if l == nil {
		return nil
	}
	return l.ListManifestsResponse
}

func (l *ListManifestsResponse) GetError() *components.Error {
	if l == nil {
		return nil
	}
	return l.Error
}
