// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0f7af438ef3a

package operations

import (
	"github.com/formancehq/fctl/internal/deployserverclient/v3/models/components"
)

// PushManifestVersionRequestBody - JSON manifest content
type PushManifestVersionRequestBody struct {
}

type PushManifestVersionRequest struct {
	ManifestID  string                         `pathParam:"style=simple,explode=false,name=manifestId"`
	RequestBody PushManifestVersionRequestBody `request:"mediaType=application/json"`
}

func (p *PushManifestVersionRequest) GetManifestID() string {
	if p == nil {
		return ""
	}
	return p.ManifestID
}

func (p *PushManifestVersionRequest) GetRequestBody() PushManifestVersionRequestBody {
	if p == nil {
		return PushManifestVersionRequestBody{}
	}
	return p.RequestBody
}

type PushManifestVersionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Manifest version created successfully
	ManifestVersionResponse *components.ManifestVersionResponse
	// Error
	Error *components.Error
}

func (p *PushManifestVersionResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PushManifestVersionResponse) GetManifestVersionResponse() *components.ManifestVersionResponse {
	if p == nil {
		return nil
	}
	return p.ManifestVersionResponse
}

func (p *PushManifestVersionResponse) GetError() *components.Error {
	if p == nil {
		return nil
	}
	return p.Error
}
