// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 998f6b496360

package operations

import (
	"github.com/formancehq/fctl/internal/deployserverclient/v3/models/components"
	"io"
)

type ReadManifestVersionRequest struct {
	ManifestID string `pathParam:"style=simple,explode=false,name=manifestId"`
	// Version number or "latest"
	Version string `pathParam:"style=simple,explode=false,name=version"`
}

func (r *ReadManifestVersionRequest) GetManifestID() string {
	if r == nil {
		return ""
	}
	return r.ManifestID
}

func (r *ReadManifestVersionRequest) GetVersion() string {
	if r == nil {
		return ""
	}
	return r.Version
}

type ReadManifestVersionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Manifest version retrieved successfully
	ManifestVersionResponse *components.ManifestVersionResponse
	// Manifest version retrieved successfully
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	ResponseStream io.ReadCloser
	// Error
	Error *components.Error
}

func (r *ReadManifestVersionResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *ReadManifestVersionResponse) GetManifestVersionResponse() *components.ManifestVersionResponse {
	if r == nil {
		return nil
	}
	return r.ManifestVersionResponse
}

func (r *ReadManifestVersionResponse) GetResponseStream() io.ReadCloser {
	if r == nil {
		return nil
	}
	return r.ResponseStream
}

func (r *ReadManifestVersionResponse) GetError() *components.Error {
	if r == nil {
		return nil
	}
	return r.Error
}
