// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1c4b97e4c0d5

package operations

import (
	"github.com/formancehq/fctl/internal/deployserverclient/v3/models/components"
	"io"
)

type ReadManifestRequest struct {
	ManifestID string `pathParam:"style=simple,explode=false,name=manifestId"`
	// Comma-separated includes (e.g. "latest" to embed latest version content)
	Include *string `queryParam:"style=form,explode=true,name=include"`
}

func (r *ReadManifestRequest) GetManifestID() string {
	if r == nil {
		return ""
	}
	return r.ManifestID
}

func (r *ReadManifestRequest) GetInclude() *string {
	if r == nil {
		return nil
	}
	return r.Include
}

type ReadManifestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Manifest retrieved successfully
	ManifestResponse *components.ManifestResponse
	// Manifest retrieved successfully
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	ResponseStream io.ReadCloser
	// Error
	Error *components.Error
}

func (r *ReadManifestResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *ReadManifestResponse) GetManifestResponse() *components.ManifestResponse {
	if r == nil {
		return nil
	}
	return r.ManifestResponse
}

func (r *ReadManifestResponse) GetResponseStream() io.ReadCloser {
	if r == nil {
		return nil
	}
	return r.ResponseStream
}

func (r *ReadManifestResponse) GetError() *components.Error {
	if r == nil {
		return nil
	}
	return r.Error
}
