// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/membershipclient/v3/internal/utils"
	"github.com/formancehq/fctl/internal/membershipclient/v3/models/components"
)

type AddFeaturesRequestBody struct {
	Features []string `json:"features"`
}

func (a *AddFeaturesRequestBody) GetFeatures() []string {
	if a == nil {
		return []string{}
	}
	return a.Features
}

type AddFeaturesRequest struct {
	OrganizationID string                  `pathParam:"style=simple,explode=false,name=organizationId"`
	Body           *AddFeaturesRequestBody `request:"mediaType=application/json"`
}

func (a AddFeaturesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AddFeaturesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AddFeaturesRequest) GetOrganizationID() string {
	if a == nil {
		return ""
	}
	return a.OrganizationID
}

func (a *AddFeaturesRequest) GetBody() *AddFeaturesRequestBody {
	if a == nil {
		return nil
	}
	return a.Body
}

type AddFeaturesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	Error *components.Error
}

func (a AddFeaturesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AddFeaturesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AddFeaturesResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AddFeaturesResponse) GetError() *components.Error {
	if a == nil {
		return nil
	}
	return a.Error
}
