// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/membershipclient/internal/utils"
	"github.com/formancehq/fctl/internal/membershipclient/models/components"
)

type AddScopeToPolicyRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	PolicyID       int64  `pathParam:"style=simple,explode=false,name=policyId"`
	ScopeID        int64  `pathParam:"style=simple,explode=false,name=scopeId"`
}

func (a *AddScopeToPolicyRequest) GetOrganizationID() string {
	if a == nil {
		return ""
	}
	return a.OrganizationID
}

func (a *AddScopeToPolicyRequest) GetPolicyID() int64 {
	if a == nil {
		return 0
	}
	return a.PolicyID
}

func (a *AddScopeToPolicyRequest) GetScopeID() int64 {
	if a == nil {
		return 0
	}
	return a.ScopeID
}

type AddScopeToPolicyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	Error *components.Error
}

func (a AddScopeToPolicyResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AddScopeToPolicyResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (a *AddScopeToPolicyResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AddScopeToPolicyResponse) GetError() *components.Error {
	if a == nil {
		return nil
	}
	return a.Error
}
