// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/membershipclient/internal/utils"
	"github.com/formancehq/fctl/internal/membershipclient/models/components"
)

type CreateOrganizationClientRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
}

func (c *CreateOrganizationClientRequest) GetOrganizationID() string {
	if c == nil {
		return ""
	}
	return c.OrganizationID
}

type CreateOrganizationClientResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Client organization created
	CreateClientResponseResponse *components.CreateClientResponseResponse
	// Error
	Error *components.Error
}

func (c CreateOrganizationClientResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateOrganizationClientResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateOrganizationClientResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateOrganizationClientResponse) GetCreateClientResponseResponse() *components.CreateClientResponseResponse {
	if c == nil {
		return nil
	}
	return c.CreateClientResponseResponse
}

func (c *CreateOrganizationClientResponse) GetError() *components.Error {
	if c == nil {
		return nil
	}
	return c.Error
}
