// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/membershipclient/internal/utils"
	"github.com/formancehq/fctl/internal/membershipclient/models/components"
)

type CreateUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// User created successfully
	CreateUserResponse *components.CreateUserResponse
	// Error
	Error *components.Error
}

func (c CreateUserResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateUserResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateUserResponse) GetCreateUserResponse() *components.CreateUserResponse {
	if c == nil {
		return nil
	}
	return c.CreateUserResponse
}

func (c *CreateUserResponse) GetError() *components.Error {
	if c == nil {
		return nil
	}
	return c.Error
}
