// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/membershipclient/v3/internal/utils"
	"github.com/formancehq/fctl/internal/membershipclient/v3/models/components"
)

type CreateStackRequest struct {
	OrganizationID string                         `pathParam:"style=simple,explode=false,name=organizationId"`
	Body           *components.CreateStackRequest `request:"mediaType=application/json"`
}

func (c CreateStackRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateStackRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateStackRequest) GetOrganizationID() string {
	if c == nil {
		return ""
	}
	return c.OrganizationID
}

func (c *CreateStackRequest) GetBody() *components.CreateStackRequest {
	if c == nil {
		return nil
	}
	return c.Body
}

type CreateStackResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Stack created
	ReadStackResponse *components.ReadStackResponse
	// Error
	Error *components.Error
}

func (c CreateStackResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateStackResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateStackResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateStackResponse) GetReadStackResponse() *components.ReadStackResponse {
	if c == nil {
		return nil
	}
	return c.ReadStackResponse
}

func (c *CreateStackResponse) GetError() *components.Error {
	if c == nil {
		return nil
	}
	return c.Error
}
