// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/v3/internal/membershipclient/internal/utils"
	"github.com/formancehq/fctl/v3/internal/membershipclient/models/components"
)

type DeclineInvitationRequest struct {
	InvitationID string `pathParam:"style=simple,explode=false,name=invitationId"`
}

func (d *DeclineInvitationRequest) GetInvitationID() string {
	if d == nil {
		return ""
	}
	return d.InvitationID
}

type DeclineInvitationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	Error *components.Error
}

func (d DeclineInvitationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeclineInvitationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeclineInvitationResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeclineInvitationResponse) GetError() *components.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
