// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/membershipclient/v3/internal/utils"
	"github.com/formancehq/fctl/internal/membershipclient/v3/models/components"
)

type DeleteStackRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	StackID        string `pathParam:"style=simple,explode=false,name=stackId"`
	Force          *bool  `queryParam:"style=form,explode=true,name=force"`
}

func (d *DeleteStackRequest) GetOrganizationID() string {
	if d == nil {
		return ""
	}
	return d.OrganizationID
}

func (d *DeleteStackRequest) GetStackID() string {
	if d == nil {
		return ""
	}
	return d.StackID
}

func (d *DeleteStackRequest) GetForce() *bool {
	if d == nil {
		return nil
	}
	return d.Force
}

type DeleteStackResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	Error *components.Error
}

func (d DeleteStackResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteStackResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteStackResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteStackResponse) GetError() *components.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
