// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/v3/internal/membershipclient/internal/utils"
	"github.com/formancehq/fctl/v3/internal/membershipclient/models/components"
)

type DeleteOrganizationClientRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
}

func (d *DeleteOrganizationClientRequest) GetOrganizationID() string {
	if d == nil {
		return ""
	}
	return d.OrganizationID
}

type DeleteOrganizationClientResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	Error *components.Error
}

func (d DeleteOrganizationClientResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteOrganizationClientResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteOrganizationClientResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteOrganizationClientResponse) GetError() *components.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
