// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/v3/internal/membershipclient/internal/utils"
	"github.com/formancehq/fctl/v3/internal/membershipclient/models/components"
)

type DeleteApplicationScopeRequest struct {
	// The unique identifier of the application (UUID format)
	ApplicationID string `pathParam:"style=simple,explode=false,name=applicationId"`
	// The unique identifier of the scope to operate on
	ScopeID int64 `pathParam:"style=simple,explode=false,name=scopeID"`
}

func (d *DeleteApplicationScopeRequest) GetApplicationID() string {
	if d == nil {
		return ""
	}
	return d.ApplicationID
}

func (d *DeleteApplicationScopeRequest) GetScopeID() int64 {
	if d == nil {
		return 0
	}
	return d.ScopeID
}

type DeleteApplicationScopeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Invalid request (invalid UUID or empty scope ID)
	Error *components.Error
}

func (d DeleteApplicationScopeResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteApplicationScopeResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteApplicationScopeResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteApplicationScopeResponse) GetError() *components.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
