// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/v3/internal/membershipclient/internal/utils"
	"github.com/formancehq/fctl/v3/internal/membershipclient/models/components"
)

type DeleteRegionRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	RegionID       string `pathParam:"style=simple,explode=false,name=regionID"`
}

func (d *DeleteRegionRequest) GetOrganizationID() string {
	if d == nil {
		return ""
	}
	return d.OrganizationID
}

func (d *DeleteRegionRequest) GetRegionID() string {
	if d == nil {
		return ""
	}
	return d.RegionID
}

type DeleteRegionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	Error *components.Error
}

func (d DeleteRegionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteRegionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteRegionResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteRegionResponse) GetError() *components.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
