// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/membershipclient/internal/utils"
	"github.com/formancehq/fctl/internal/membershipclient/models/components"
)

type DisableApplicationForOrganizationRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	ApplicationID  string `pathParam:"style=simple,explode=false,name=applicationId"`
}

func (d *DisableApplicationForOrganizationRequest) GetOrganizationID() string {
	if d == nil {
		return ""
	}
	return d.OrganizationID
}

func (d *DisableApplicationForOrganizationRequest) GetApplicationID() string {
	if d == nil {
		return ""
	}
	return d.ApplicationID
}

type DisableApplicationForOrganizationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	Error *components.Error
}

func (d DisableApplicationForOrganizationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DisableApplicationForOrganizationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DisableApplicationForOrganizationResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DisableApplicationForOrganizationResponse) GetError() *components.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
