// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/membershipclient/internal/utils"
	"github.com/formancehq/fctl/internal/membershipclient/models/components"
)

type GetOrganizationApplicationRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	ApplicationID  string `pathParam:"style=simple,explode=false,name=applicationId"`
}

func (g *GetOrganizationApplicationRequest) GetOrganizationID() string {
	if g == nil {
		return ""
	}
	return g.OrganizationID
}

func (g *GetOrganizationApplicationRequest) GetApplicationID() string {
	if g == nil {
		return ""
	}
	return g.ApplicationID
}

type GetOrganizationApplicationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Application details
	GetApplicationResponse *components.GetApplicationResponse
	// Error
	Error *components.Error
}

func (g GetOrganizationApplicationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetOrganizationApplicationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (g *GetOrganizationApplicationResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetOrganizationApplicationResponse) GetGetApplicationResponse() *components.GetApplicationResponse {
	if g == nil {
		return nil
	}
	return g.GetApplicationResponse
}

func (g *GetOrganizationApplicationResponse) GetError() *components.Error {
	if g == nil {
		return nil
	}
	return g.Error
}
