// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/membershipclient/internal/utils"
	"github.com/formancehq/fctl/internal/membershipclient/models/components"
)

type GetServerInfoResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Server information
	ServerInfo *components.ServerInfo
	// Error
	Error *components.Error
}

func (g GetServerInfoResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetServerInfoResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (g *GetServerInfoResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetServerInfoResponse) GetServerInfo() *components.ServerInfo {
	if g == nil {
		return nil
	}
	return g.ServerInfo
}

func (g *GetServerInfoResponse) GetError() *components.Error {
	if g == nil {
		return nil
	}
	return g.Error
}
