// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/membershipclient/internal/utils"
	"github.com/formancehq/fctl/internal/membershipclient/models/components"
)

type GetStackRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	StackID        string `pathParam:"style=simple,explode=false,name=stackId"`
}

func (g *GetStackRequest) GetOrganizationID() string {
	if g == nil {
		return ""
	}
	return g.OrganizationID
}

func (g *GetStackRequest) GetStackID() string {
	if g == nil {
		return ""
	}
	return g.StackID
}

type GetStackResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	CreateStackResponse *components.CreateStackResponse
	// Error
	Error *components.Error
}

func (g GetStackResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetStackResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetStackResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetStackResponse) GetCreateStackResponse() *components.CreateStackResponse {
	if g == nil {
		return nil
	}
	return g.CreateStackResponse
}

func (g *GetStackResponse) GetError() *components.Error {
	if g == nil {
		return nil
	}
	return g.Error
}
