// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/membershipclient/internal/utils"
	"github.com/formancehq/fctl/internal/membershipclient/models/components"
)

type ListUsersOfOrganizationRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
}

func (l *ListUsersOfOrganizationRequest) GetOrganizationID() string {
	if l == nil {
		return ""
	}
	return l.OrganizationID
}

type ListUsersOfOrganizationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of users
	ListUsersResponse *components.ListUsersResponse
	// Error
	Error *components.Error
}

func (l ListUsersOfOrganizationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListUsersOfOrganizationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListUsersOfOrganizationResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListUsersOfOrganizationResponse) GetListUsersResponse() *components.ListUsersResponse {
	if l == nil {
		return nil
	}
	return l.ListUsersResponse
}

func (l *ListUsersOfOrganizationResponse) GetError() *components.Error {
	if l == nil {
		return nil
	}
	return l.Error
}
