// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/membershipclient/internal/utils"
	"github.com/formancehq/fctl/internal/membershipclient/models/components"
)

type ListApplicationsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of applications
	ListApplicationsResponse *components.ListApplicationsResponse
	// Error
	Error *components.Error
}

func (l ListApplicationsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListApplicationsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (l *ListApplicationsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListApplicationsResponse) GetListApplicationsResponse() *components.ListApplicationsResponse {
	if l == nil {
		return nil
	}
	return l.ListApplicationsResponse
}

func (l *ListApplicationsResponse) GetError() *components.Error {
	if l == nil {
		return nil
	}
	return l.Error
}
