// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/membershipclient/internal/utils"
	"github.com/formancehq/fctl/internal/membershipclient/models/components"
)

type OrganizationClientsReadRequest struct {
	OrganizationID string  `pathParam:"style=simple,explode=false,name=organizationId"`
	Cursor         *string `queryParam:"style=form,explode=true,name=cursor"`
	PageSize       *int64  `queryParam:"style=form,explode=true,name=pageSize"`
}

func (o *OrganizationClientsReadRequest) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

func (o *OrganizationClientsReadRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

func (o *OrganizationClientsReadRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

type OrganizationClientsReadResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Organization client
	ReadOrganizationClientsResponse *components.ReadOrganizationClientsResponse
	// Error
	Error *components.Error
}

func (o OrganizationClientsReadResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationClientsReadResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationClientsReadResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OrganizationClientsReadResponse) GetReadOrganizationClientsResponse() *components.ReadOrganizationClientsResponse {
	if o == nil {
		return nil
	}
	return o.ReadOrganizationClientsResponse
}

func (o *OrganizationClientsReadResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
