// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/v3/internal/membershipclient/internal/utils"
	"github.com/formancehq/fctl/v3/internal/membershipclient/models/components"
)

type OrganizationClientReadRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	ClientID       string `pathParam:"style=simple,explode=false,name=clientId"`
}

func (o *OrganizationClientReadRequest) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

func (o *OrganizationClientReadRequest) GetClientID() string {
	if o == nil {
		return ""
	}
	return o.ClientID
}

type OrganizationClientReadResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Organization client details
	ReadOrganizationClientResponse *components.ReadOrganizationClientResponse
	// Error
	Error *components.Error
}

func (o OrganizationClientReadResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationClientReadResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationClientReadResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OrganizationClientReadResponse) GetReadOrganizationClientResponse() *components.ReadOrganizationClientResponse {
	if o == nil {
		return nil
	}
	return o.ReadOrganizationClientResponse
}

func (o *OrganizationClientReadResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
