// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/membershipclient/internal/utils"
	"github.com/formancehq/fctl/internal/membershipclient/models/components"
)

type OrganizationClientUpdateRequest struct {
	OrganizationID string                                      `pathParam:"style=simple,explode=false,name=organizationId"`
	ClientID       string                                      `pathParam:"style=simple,explode=false,name=clientId"`
	Body           *components.UpdateOrganizationClientRequest `request:"mediaType=application/json"`
}

func (o OrganizationClientUpdateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationClientUpdateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationClientUpdateRequest) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

func (o *OrganizationClientUpdateRequest) GetClientID() string {
	if o == nil {
		return ""
	}
	return o.ClientID
}

func (o *OrganizationClientUpdateRequest) GetBody() *components.UpdateOrganizationClientRequest {
	if o == nil {
		return nil
	}
	return o.Body
}

type OrganizationClientUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	Error *components.Error
}

func (o OrganizationClientUpdateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationClientUpdateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationClientUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OrganizationClientUpdateResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
