// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/membershipclient/v3/internal/utils"
	"github.com/formancehq/fctl/internal/membershipclient/v3/models/components"
)

type ReadAuthenticationProviderRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
}

func (r *ReadAuthenticationProviderRequest) GetOrganizationID() string {
	if r == nil {
		return ""
	}
	return r.OrganizationID
}

type ReadAuthenticationProviderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Authentication provider details
	AuthenticationProviderResponse *components.AuthenticationProviderResponse
	// Error
	Error *components.Error
}

func (r ReadAuthenticationProviderResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReadAuthenticationProviderResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReadAuthenticationProviderResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *ReadAuthenticationProviderResponse) GetAuthenticationProviderResponse() *components.AuthenticationProviderResponse {
	if r == nil {
		return nil
	}
	return r.AuthenticationProviderResponse
}

func (r *ReadAuthenticationProviderResponse) GetError() *components.Error {
	if r == nil {
		return nil
	}
	return r.Error
}
