// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/membershipclient/v3/internal/utils"
	"github.com/formancehq/fctl/internal/membershipclient/v3/models/components"
)

type ReadUserOfOrganizationRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	UserID         string `pathParam:"style=simple,explode=false,name=userId"`
}

func (r *ReadUserOfOrganizationRequest) GetOrganizationID() string {
	if r == nil {
		return ""
	}
	return r.OrganizationID
}

func (r *ReadUserOfOrganizationRequest) GetUserID() string {
	if r == nil {
		return ""
	}
	return r.UserID
}

type ReadUserOfOrganizationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Read a user
	ReadOrganizationUserResponse *components.ReadOrganizationUserResponse
	// Error
	Error *components.Error
}

func (r ReadUserOfOrganizationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReadUserOfOrganizationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReadUserOfOrganizationResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *ReadUserOfOrganizationResponse) GetReadOrganizationUserResponse() *components.ReadOrganizationUserResponse {
	if r == nil {
		return nil
	}
	return r.ReadOrganizationUserResponse
}

func (r *ReadUserOfOrganizationResponse) GetError() *components.Error {
	if r == nil {
		return nil
	}
	return r.Error
}
