// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/v3/internal/membershipclient/internal/utils"
	"github.com/formancehq/fctl/v3/internal/membershipclient/models/components"
)

type ReadConnectedUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Read a user
	ReadUserResponse *components.ReadUserResponse
	// Error
	Error *components.Error
}

func (r ReadConnectedUserResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReadConnectedUserResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReadConnectedUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *ReadConnectedUserResponse) GetReadUserResponse() *components.ReadUserResponse {
	if r == nil {
		return nil
	}
	return r.ReadUserResponse
}

func (r *ReadConnectedUserResponse) GetError() *components.Error {
	if r == nil {
		return nil
	}
	return r.Error
}
