// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/membershipclient/internal/utils"
	"github.com/formancehq/fctl/internal/membershipclient/models/components"
)

type RemoveDelegationFromScopeRequest struct {
	// The unique identifier of the application (UUID format)
	ApplicationID string `pathParam:"style=simple,explode=false,name=applicationId"`
	// The unique identifier of the scope to operate on
	ScopeID int64 `pathParam:"style=simple,explode=false,name=scopeID"`
	// The ID of the organization scope that this scope delegates to
	DelegatesToScopeID int64 `pathParam:"style=simple,explode=false,name=delegatesToScopeId"`
}

func (r *RemoveDelegationFromScopeRequest) GetApplicationID() string {
	if r == nil {
		return ""
	}
	return r.ApplicationID
}

func (r *RemoveDelegationFromScopeRequest) GetScopeID() int64 {
	if r == nil {
		return 0
	}
	return r.ScopeID
}

func (r *RemoveDelegationFromScopeRequest) GetDelegatesToScopeID() int64 {
	if r == nil {
		return 0
	}
	return r.DelegatesToScopeID
}

type RemoveDelegationFromScopeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	Error *components.Error
}

func (r RemoveDelegationFromScopeResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RemoveDelegationFromScopeResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RemoveDelegationFromScopeResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RemoveDelegationFromScopeResponse) GetError() *components.Error {
	if r == nil {
		return nil
	}
	return r.Error
}
