// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/membershipclient/internal/utils"
	"github.com/formancehq/fctl/internal/membershipclient/models/components"
)

type UpdatePolicyRequest struct {
	OrganizationID string                 `pathParam:"style=simple,explode=false,name=organizationId"`
	PolicyID       int64                  `pathParam:"style=simple,explode=false,name=policyId"`
	Body           *components.PolicyData `request:"mediaType=application/json"`
}

func (u UpdatePolicyRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdatePolicyRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdatePolicyRequest) GetOrganizationID() string {
	if u == nil {
		return ""
	}
	return u.OrganizationID
}

func (u *UpdatePolicyRequest) GetPolicyID() int64 {
	if u == nil {
		return 0
	}
	return u.PolicyID
}

func (u *UpdatePolicyRequest) GetBody() *components.PolicyData {
	if u == nil {
		return nil
	}
	return u.Body
}

type UpdatePolicyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Policy updated
	UpdatePolicyResponse *components.UpdatePolicyResponse
	// Error
	Error *components.Error
}

func (u UpdatePolicyResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdatePolicyResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdatePolicyResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdatePolicyResponse) GetUpdatePolicyResponse() *components.UpdatePolicyResponse {
	if u == nil {
		return nil
	}
	return u.UpdatePolicyResponse
}

func (u *UpdatePolicyResponse) GetError() *components.Error {
	if u == nil {
		return nil
	}
	return u.Error
}
