// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/membershipclient/internal/utils"
	"github.com/formancehq/fctl/internal/membershipclient/models/components"
)

type UpdateStackRequest struct {
	OrganizationID string                `pathParam:"style=simple,explode=false,name=organizationId"`
	StackID        string                `pathParam:"style=simple,explode=false,name=stackId"`
	Body           *components.StackData `request:"mediaType=application/json"`
}

func (u UpdateStackRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateStackRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateStackRequest) GetOrganizationID() string {
	if u == nil {
		return ""
	}
	return u.OrganizationID
}

func (u *UpdateStackRequest) GetStackID() string {
	if u == nil {
		return ""
	}
	return u.StackID
}

func (u *UpdateStackRequest) GetBody() *components.StackData {
	if u == nil {
		return nil
	}
	return u.Body
}

type UpdateStackResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Updated stack
	ReadStackResponse *components.ReadStackResponse
	// Error
	Error *components.Error
}

func (u UpdateStackResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateStackResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateStackResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateStackResponse) GetReadStackResponse() *components.ReadStackResponse {
	if u == nil {
		return nil
	}
	return u.ReadStackResponse
}

func (u *UpdateStackResponse) GetError() *components.Error {
	if u == nil {
		return nil
	}
	return u.Error
}
