// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/membershipclient/internal/utils"
	"github.com/formancehq/fctl/internal/membershipclient/models/components"
)

type UpsertOrganizationUserRequest struct {
	OrganizationID string                                    `pathParam:"style=simple,explode=false,name=organizationId"`
	UserID         string                                    `pathParam:"style=simple,explode=false,name=userId"`
	Body           *components.UpdateOrganizationUserRequest `request:"mediaType=application/json"`
}

func (u UpsertOrganizationUserRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpsertOrganizationUserRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpsertOrganizationUserRequest) GetOrganizationID() string {
	if u == nil {
		return ""
	}
	return u.OrganizationID
}

func (u *UpsertOrganizationUserRequest) GetUserID() string {
	if u == nil {
		return ""
	}
	return u.UserID
}

func (u *UpsertOrganizationUserRequest) GetBody() *components.UpdateOrganizationUserRequest {
	if u == nil {
		return nil
	}
	return u.Body
}

type UpsertOrganizationUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	Error *components.Error
}

func (u UpsertOrganizationUserResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpsertOrganizationUserResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpsertOrganizationUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpsertOrganizationUserResponse) GetError() *components.Error {
	if u == nil {
		return nil
	}
	return u.Error
}
