// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 28d697942062

package components

type Application struct {
	Ledgers        []Ledger        `json:"ledgers,omitempty"`
	Payments       *Payments       `json:"payments,omitempty"`
	Reconciliation *Reconciliation `json:"reconciliation,omitempty"`
	Stack          Stack           `json:"stack"`
	Webhooks       []Webhook       `json:"webhooks,omitempty"`
}

func (a *Application) GetLedgers() []Ledger {
	if a == nil {
		return nil
	}
	return a.Ledgers
}

func (a *Application) GetPayments() *Payments {
	if a == nil {
		return nil
	}
	return a.Payments
}

func (a *Application) GetReconciliation() *Reconciliation {
	if a == nil {
		return nil
	}
	return a.Reconciliation
}

func (a *Application) GetStack() Stack {
	if a == nil {
		return Stack{}
	}
	return a.Stack
}

func (a *Application) GetWebhooks() []Webhook {
	if a == nil {
		return nil
	}
	return a.Webhooks
}
