// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9210c43db58e

package components

import (
	"encoding/json"
	"fmt"
)

// Kind - - `undeployed`: the app has a manifest bound but no successful deployment yet.
// - `synced`: deployed (manifestId, version) matches the bound manifest's latest version.
// - `behind`: deployed manifest matches the bound manifest but on an older version.
// - `rebound`: the app was rebound; deployed manifest is a different manifest.
type Kind string

const (
	KindUndeployed Kind = "undeployed"
	KindSynced     Kind = "synced"
	KindBehind     Kind = "behind"
	KindRebound    Kind = "rebound"
)

func (e Kind) ToPointer() *Kind {
	return &e
}
func (e *Kind) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "undeployed":
		fallthrough
	case "synced":
		fallthrough
	case "behind":
		fallthrough
	case "rebound":
		*e = Kind(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Kind: %v", v)
	}
}

// AppManifestDivergence - Relationship between the app's bound manifest and what's currently
// deployed (last `applied` deployment, ignoring destroys).
type AppManifestDivergence struct {
	// - `undeployed`: the app has a manifest bound but no successful deployment yet.
	// - `synced`: deployed (manifestId, version) matches the bound manifest's latest version.
	// - `behind`: deployed manifest matches the bound manifest but on an older version.
	// - `rebound`: the app was rebound; deployed manifest is a different manifest.
	//
	Kind Kind `json:"kind"`
	// ID of the manifest reflected in the most recent applied deployment
	DeployedManifestID *string `json:"deployedManifestId,omitempty"`
	// Version reflected in the most recent applied deployment
	DeployedVersion *int64 `json:"deployedVersion,omitempty"`
	// Latest version available in the bound manifest's lineage
	LatestVersion int64 `json:"latestVersion"`
}

func (a *AppManifestDivergence) GetKind() Kind {
	if a == nil {
		return Kind("")
	}
	return a.Kind
}

func (a *AppManifestDivergence) GetDeployedManifestID() *string {
	if a == nil {
		return nil
	}
	return a.DeployedManifestID
}

func (a *AppManifestDivergence) GetDeployedVersion() *int64 {
	if a == nil {
		return nil
	}
	return a.DeployedVersion
}

func (a *AppManifestDivergence) GetLatestVersion() int64 {
	if a == nil {
		return 0
	}
	return a.LatestVersion
}
