// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d9b2be34c541

package components

import (
	"github.com/formancehq/fctl/internal/deployserverclient/v3/internal/utils"
	"time"
)

type CreateManifestResponseData struct {
	ID        string    `json:"id"`
	AppID     *string   `json:"appId,omitempty"`
	Version   int64     `json:"version"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"createdAt"`
}

func (c CreateManifestResponseData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateManifestResponseData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateManifestResponseData) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateManifestResponseData) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

func (c *CreateManifestResponseData) GetVersion() int64 {
	if c == nil {
		return 0
	}
	return c.Version
}

func (c *CreateManifestResponseData) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateManifestResponseData) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

type CreateManifestResponse struct {
	Data CreateManifestResponseData `json:"data"`
}

func (c *CreateManifestResponse) GetData() CreateManifestResponseData {
	if c == nil {
		return CreateManifestResponseData{}
	}
	return c.Data
}
