// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d50be5cb7391

package components

type State struct {
	// The stack details from the Terraform state
	Stack map[string]any `json:"stack"`
}

func (s *State) GetStack() map[string]any {
	if s == nil {
		return map[string]any{}
	}
	return s.Stack
}
