// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 703496f103a6

package components

type VariableData struct {
	// Key of the variable
	Key string `json:"key"`
	// Value of the variable
	Value string `json:"value"`
	// Description of the variable
	Description *string `json:"description,omitempty"`
	// Whether the variable is sensitive
	Sensitive bool `json:"sensitive"`
}

func (v *VariableData) GetKey() string {
	if v == nil {
		return ""
	}
	return v.Key
}

func (v *VariableData) GetValue() string {
	if v == nil {
		return ""
	}
	return v.Value
}

func (v *VariableData) GetDescription() *string {
	if v == nil {
		return nil
	}
	return v.Description
}

func (v *VariableData) GetSensitive() bool {
	if v == nil {
		return false
	}
	return v.Sensitive
}
