// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5575cc5558ac

package components

type App struct {
	// Unique identifier for the app
	ID string `json:"id"`
	// Name of the app
	Name string `json:"name"`
	// Optional existing stack ID claimed by this app
	StackID *string `json:"stackId,omitempty"`
	State   *State  `json:"state,omitempty"`
}

func (a *App) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *App) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *App) GetStackID() *string {
	if a == nil {
		return nil
	}
	return a.StackID
}

func (a *App) GetState() *State {
	if a == nil {
		return nil
	}
	return a.State
}
