// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AppInfo struct {
	Name     *string `json:"name,omitempty"`
	RegionID *string `json:"region_id,omitempty"`
	Version  *string `json:"version,omitempty"`
}

func (o *AppInfo) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *AppInfo) GetRegionID() *string {
	if o == nil {
		return nil
	}
	return o.RegionID
}

func (o *AppInfo) GetVersion() *string {
	if o == nil {
		return nil
	}
	return o.Version
}
