// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AppInfo struct {
	Name     *string `json:"name,omitempty"`
	RegionID *string `json:"region_id,omitempty"`
	Version  *string `json:"version,omitempty"`
}

func (a *AppInfo) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}

func (a *AppInfo) GetRegionID() *string {
	if a == nil {
		return nil
	}
	return a.RegionID
}

func (a *AppInfo) GetVersion() *string {
	if a == nil {
		return nil
	}
	return a.Version
}
