// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Application struct {
	Events         *Webhooks       `json:"events,omitempty"`
	Info           *AppInfo        `json:"info,omitempty"`
	Ledger         []Ledger        `json:"ledger,omitempty"`
	Payments       *Payments       `json:"payments,omitempty"`
	Reconciliation *Reconciliation `json:"reconciliation,omitempty"`
}

func (o *Application) GetEvents() *Webhooks {
	if o == nil {
		return nil
	}
	return o.Events
}

func (o *Application) GetInfo() *AppInfo {
	if o == nil {
		return nil
	}
	return o.Info
}

func (o *Application) GetLedger() []Ledger {
	if o == nil {
		return nil
	}
	return o.Ledger
}

func (o *Application) GetPayments() *Payments {
	if o == nil {
		return nil
	}
	return o.Payments
}

func (o *Application) GetReconciliation() *Reconciliation {
	if o == nil {
		return nil
	}
	return o.Reconciliation
}
