// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AppResponse struct {
	Data App `json:"data"`
}

func (a *AppResponse) GetData() App {
	if a == nil {
		return App{}
	}
	return a.Data
}
