// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AppResponse struct {
	Data App `json:"data"`
}

func (o *AppResponse) GetData() App {
	if o == nil {
		return App{}
	}
	return o.Data
}
