// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AppVersionResponse struct {
	Data ConfigurationVersion `json:"data"`
}

func (o *AppVersionResponse) GetData() ConfigurationVersion {
	if o == nil {
		return ConfigurationVersion{}
	}
	return o.Data
}
