// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateVariableResponse struct {
	Data Variable `json:"data"`
}

func (c *CreateVariableResponse) GetData() Variable {
	if c == nil {
		return Variable{}
	}
	return c.Data
}
