// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateVariableRequest struct {
	Variable VariableData `json:"variable"`
}

func (o *CreateVariableRequest) GetVariable() VariableData {
	if o == nil {
		return VariableData{}
	}
	return o.Variable
}
