// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: de6e097ab360

package components

type DeleteAppResponse struct {
	// ID of the destroy deployment enqueued to clean up the app's
	// resources. Empty when no destroy was needed (e.g. no prior
	// applied deployment). Use `GET /deployments/{id}` to poll its
	// status.
	//
	DestroyDeploymentID *string `json:"destroyDeploymentId,omitempty"`
}

func (d *DeleteAppResponse) GetDestroyDeploymentID() *string {
	if d == nil {
		return nil
	}
	return d.DestroyDeploymentID
}
