// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 38a6c1aca4c2

package components

type DeploymentResponse struct {
	Data DeploymentResource `json:"data"`
}

func (d *DeploymentResponse) GetData() DeploymentResource {
	if d == nil {
		return DeploymentResource{}
	}
	return d.Data
}
