// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3e9aea6345f2

package components

// ListManifestVersionsResponseCursor - Cursor pagination envelope. `next` and `previous` are opaque tokens
// produced by the server; pass them back as `?cursor=` to fetch the
// adjacent page. `hasMore` is `true` when more results exist after the
// current page. `pageSize` echoes the page size used for this page.
type ListManifestVersionsResponseCursor struct {
	// Number of items requested for this page
	PageSize *int64 `json:"pageSize,omitempty"`
	// True when more results exist after this page
	HasMore bool `json:"hasMore"`
	// Opaque cursor token for the previous page (empty when none)
	Previous *string `json:"previous,omitempty"`
	// Opaque cursor token for the next page (empty when none)
	Next *string           `json:"next,omitempty"`
	Data []ManifestVersion `json:"data"`
}

func (l *ListManifestVersionsResponseCursor) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

func (l *ListManifestVersionsResponseCursor) GetHasMore() bool {
	if l == nil {
		return false
	}
	return l.HasMore
}

func (l *ListManifestVersionsResponseCursor) GetPrevious() *string {
	if l == nil {
		return nil
	}
	return l.Previous
}

func (l *ListManifestVersionsResponseCursor) GetNext() *string {
	if l == nil {
		return nil
	}
	return l.Next
}

func (l *ListManifestVersionsResponseCursor) GetData() []ManifestVersion {
	if l == nil {
		return []ManifestVersion{}
	}
	return l.Data
}

type ListManifestVersionsResponse struct {
	Cursor ListManifestVersionsResponseCursor `json:"cursor"`
}

func (l *ListManifestVersionsResponse) GetCursor() ListManifestVersionsResponseCursor {
	if l == nil {
		return ListManifestVersionsResponseCursor{}
	}
	return l.Cursor
}
