// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListAppsResponseData struct {
	// Current page number
	CurrentPage *int64 `json:"currentPage,omitempty"`
	// Previous page number
	PreviousPage *int64 `json:"previousPage,omitempty"`
	// Next page number
	NextPage *int64 `json:"nextPage,omitempty"`
	// Total number of pages
	TotalPages *int64 `json:"totalPages,omitempty"`
	// Total number of items
	TotalCount *int64 `json:"totalCount,omitempty"`
	Items      []App  `json:"items"`
}

func (o *ListAppsResponseData) GetCurrentPage() *int64 {
	if o == nil {
		return nil
	}
	return o.CurrentPage
}

func (o *ListAppsResponseData) GetPreviousPage() *int64 {
	if o == nil {
		return nil
	}
	return o.PreviousPage
}

func (o *ListAppsResponseData) GetNextPage() *int64 {
	if o == nil {
		return nil
	}
	return o.NextPage
}

func (o *ListAppsResponseData) GetTotalPages() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalPages
}

func (o *ListAppsResponseData) GetTotalCount() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalCount
}

func (o *ListAppsResponseData) GetItems() []App {
	if o == nil {
		return []App{}
	}
	return o.Items
}

type ListAppsResponse struct {
	Data ListAppsResponseData `json:"data"`
}

func (o *ListAppsResponse) GetData() ListAppsResponseData {
	if o == nil {
		return ListAppsResponseData{}
	}
	return o.Data
}
