// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListRunsResponseData struct {
	// Current page number
	CurrentPage *int64 `json:"currentPage,omitempty"`
	// Previous page number
	PreviousPage *int64 `json:"previousPage,omitempty"`
	// Next page number
	NextPage *int64 `json:"nextPage,omitempty"`
	// Total number of pages
	TotalPages *int64 `json:"totalPages,omitempty"`
	// Total number of items
	TotalCount *int64 `json:"totalCount,omitempty"`
	Items      []Run  `json:"items"`
}

func (l *ListRunsResponseData) GetCurrentPage() *int64 {
	if l == nil {
		return nil
	}
	return l.CurrentPage
}

func (l *ListRunsResponseData) GetPreviousPage() *int64 {
	if l == nil {
		return nil
	}
	return l.PreviousPage
}

func (l *ListRunsResponseData) GetNextPage() *int64 {
	if l == nil {
		return nil
	}
	return l.NextPage
}

func (l *ListRunsResponseData) GetTotalPages() *int64 {
	if l == nil {
		return nil
	}
	return l.TotalPages
}

func (l *ListRunsResponseData) GetTotalCount() *int64 {
	if l == nil {
		return nil
	}
	return l.TotalCount
}

func (l *ListRunsResponseData) GetItems() []Run {
	if l == nil {
		return []Run{}
	}
	return l.Items
}

type ListRunsResponse struct {
	Data ListRunsResponseData `json:"data"`
}

func (l *ListRunsResponse) GetData() ListRunsResponseData {
	if l == nil {
		return ListRunsResponseData{}
	}
	return l.Data
}
