// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/fctl/internal/deployserverclient/internal/utils"
	"time"
)

// Diagnostic - Detailed log message
type Diagnostic struct {
	// Severity of the log message
	Severity string `json:"severity"`
	Detail   string `json:"detail"`
	// Brief summary of the log message
	Summary string `json:"summary"`
}

func (o *Diagnostic) GetSeverity() string {
	if o == nil {
		return ""
	}
	return o.Severity
}

func (o *Diagnostic) GetDetail() string {
	if o == nil {
		return ""
	}
	return o.Detail
}

func (o *Diagnostic) GetSummary() string {
	if o == nil {
		return ""
	}
	return o.Summary
}

type Log struct {
	// Log message
	Message string `json:"message"`
	// Timestamp when the log was created
	Timestamp time.Time `json:"timestamp"`
	// Module or component that generated the log
	Module string `json:"module"`
	// Detailed log message
	Diagnostic *Diagnostic `json:"diagnostic,omitempty"`
}

func (l Log) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *Log) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Log) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *Log) GetTimestamp() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.Timestamp
}

func (o *Log) GetModule() string {
	if o == nil {
		return ""
	}
	return o.Module
}

func (o *Log) GetDiagnostic() *Diagnostic {
	if o == nil {
		return nil
	}
	return o.Diagnostic
}
