// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a45a7b58ee06

package components

import (
	"github.com/formancehq/fctl/internal/deployserverclient/v3/internal/utils"
	"time"
)

type ManifestVersion struct {
	// ID of the manifest this version belongs to
	ManifestID string `json:"manifestId"`
	// Version number
	Version int64 `json:"version"`
	// Manifest content (base64-encoded). Null when listing versions, present when reading a specific version.
	Content *string `json:"content,omitempty"`
	// Timestamp when the version was created
	CreatedAt time.Time `json:"createdAt"`
}

func (m ManifestVersion) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *ManifestVersion) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *ManifestVersion) GetManifestID() string {
	if m == nil {
		return ""
	}
	return m.ManifestID
}

func (m *ManifestVersion) GetVersion() int64 {
	if m == nil {
		return 0
	}
	return m.Version
}

func (m *ManifestVersion) GetContent() *string {
	if m == nil {
		return nil
	}
	return m.Content
}

func (m *ManifestVersion) GetCreatedAt() time.Time {
	if m == nil {
		return time.Time{}
	}
	return m.CreatedAt
}
