// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 813ef73c5fb1

package components

type Connector struct {
	Configuration map[string]any    `json:"configuration,omitempty"`
	Credentials   map[string]string `json:"credentials,omitempty"`
	Name          string            `json:"name"`
	Provider      string            `json:"provider"`
}

func (c *Connector) GetConfiguration() map[string]any {
	if c == nil {
		return nil
	}
	return c.Configuration
}

func (c *Connector) GetCredentials() map[string]string {
	if c == nil {
		return nil
	}
	return c.Credentials
}

func (c *Connector) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *Connector) GetProvider() string {
	if c == nil {
		return ""
	}
	return c.Provider
}

type Payments struct {
	Connectors []Connector     `json:"connectors,omitempty"`
	Pools      map[string]Pool `json:"pools,omitempty"`
}

func (p *Payments) GetConnectors() []Connector {
	if p == nil {
		return nil
	}
	return p.Connectors
}

func (p *Payments) GetPools() map[string]Pool {
	if p == nil {
		return nil
	}
	return p.Pools
}
