// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 52814f15349a

package components

type Pool struct {
	AccountIds []string       `json:"accountIds,omitempty"`
	Query      map[string]any `json:"query,omitempty"`
}

func (p *Pool) GetAccountIds() []string {
	if p == nil {
		return nil
	}
	return p.AccountIds
}

func (p *Pool) GetQuery() map[string]any {
	if p == nil {
		return nil
	}
	return p.Query
}
