// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Pool struct {
	AccountIds []string `json:"accountIds,omitempty"`
}

func (p *Pool) GetAccountIds() []string {
	if p == nil {
		return nil
	}
	return p.AccountIds
}
