// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d31e5b963c16

package components

// ReadVariablesResponseCursor - Cursor pagination envelope. `next` and `previous` are opaque tokens
// produced by the server; pass them back as `?cursor=` to fetch the
// adjacent page. `hasMore` is `true` when more results exist after the
// current page. `pageSize` echoes the page size used for this page.
type ReadVariablesResponseCursor struct {
	// Number of items requested for this page
	PageSize *int64 `json:"pageSize,omitempty"`
	// True when more results exist after this page
	HasMore bool `json:"hasMore"`
	// Opaque cursor token for the previous page (empty when none)
	Previous *string `json:"previous,omitempty"`
	// Opaque cursor token for the next page (empty when none)
	Next *string    `json:"next,omitempty"`
	Data []Variable `json:"data"`
}

func (r *ReadVariablesResponseCursor) GetPageSize() *int64 {
	if r == nil {
		return nil
	}
	return r.PageSize
}

func (r *ReadVariablesResponseCursor) GetHasMore() bool {
	if r == nil {
		return false
	}
	return r.HasMore
}

func (r *ReadVariablesResponseCursor) GetPrevious() *string {
	if r == nil {
		return nil
	}
	return r.Previous
}

func (r *ReadVariablesResponseCursor) GetNext() *string {
	if r == nil {
		return nil
	}
	return r.Next
}

func (r *ReadVariablesResponseCursor) GetData() []Variable {
	if r == nil {
		return []Variable{}
	}
	return r.Data
}

type ReadVariablesResponse struct {
	Cursor ReadVariablesResponseCursor `json:"cursor"`
}

func (r *ReadVariablesResponse) GetCursor() ReadVariablesResponseCursor {
	if r == nil {
		return ReadVariablesResponseCursor{}
	}
	return r.Cursor
}
