// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ReadLogsResponse struct {
	Data []Log `json:"data,omitempty"`
}

func (r *ReadLogsResponse) GetData() []Log {
	if r == nil {
		return nil
	}
	return r.Data
}
