// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ReadVariablesResponseData struct {
	Items []Variable `json:"items,omitempty"`
	// Current page number
	CurrentPage *int64 `json:"currentPage,omitempty"`
	// Previous page number
	PreviousPage *int64 `json:"previousPage,omitempty"`
	// Next page number
	NextPage *int64 `json:"nextPage,omitempty"`
	// Total number of pages
	TotalPages *int64 `json:"totalPages,omitempty"`
	// Total number of items
	TotalCount *int64 `json:"totalCount,omitempty"`
}

func (o *ReadVariablesResponseData) GetItems() []Variable {
	if o == nil {
		return nil
	}
	return o.Items
}

func (o *ReadVariablesResponseData) GetCurrentPage() *int64 {
	if o == nil {
		return nil
	}
	return o.CurrentPage
}

func (o *ReadVariablesResponseData) GetPreviousPage() *int64 {
	if o == nil {
		return nil
	}
	return o.PreviousPage
}

func (o *ReadVariablesResponseData) GetNextPage() *int64 {
	if o == nil {
		return nil
	}
	return o.NextPage
}

func (o *ReadVariablesResponseData) GetTotalPages() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalPages
}

func (o *ReadVariablesResponseData) GetTotalCount() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalCount
}

type ReadVariablesResponse struct {
	Data ReadVariablesResponseData `json:"data"`
}

func (o *ReadVariablesResponse) GetData() ReadVariablesResponseData {
	if o == nil {
		return ReadVariablesResponseData{}
	}
	return o.Data
}
