// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ReadStateResponse struct {
	Data State `json:"data"`
}

func (r *ReadStateResponse) GetData() State {
	if r == nil {
		return State{}
	}
	return r.Data
}
