// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ReconciliationPolicy struct {
	Ledger ReconciliationLedger `json:"ledger"`
	Name   string               `json:"name"`
	Pool   string               `json:"pool"`
}

func (r *ReconciliationPolicy) GetLedger() ReconciliationLedger {
	if r == nil {
		return ReconciliationLedger{}
	}
	return r.Ledger
}

func (r *ReconciliationPolicy) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *ReconciliationPolicy) GetPool() string {
	if r == nil {
		return ""
	}
	return r.Pool
}
