// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Reconciliation struct {
	Policies []ReconciliationPolicy `json:"policies,omitempty"`
}

func (r *Reconciliation) GetPolicies() []ReconciliationPolicy {
	if r == nil {
		return nil
	}
	return r.Policies
}
