// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ReconciliationPolicy struct {
	Ledger *ReconciliationLedger `json:"ledger,omitempty"`
	Name   *string               `json:"name,omitempty"`
	Pool   *string               `json:"pool,omitempty"`
}

func (o *ReconciliationPolicy) GetLedger() *ReconciliationLedger {
	if o == nil {
		return nil
	}
	return o.Ledger
}

func (o *ReconciliationPolicy) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *ReconciliationPolicy) GetPool() *string {
	if o == nil {
		return nil
	}
	return o.Pool
}
