// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/fctl/internal/deployserverclient/internal/utils"
	"time"
)

type Run struct {
	// Unique identifier for the run
	ID string `json:"id"`
	// Whether the run was auto-applied
	AutoApply bool `json:"autoApply"`
	// Timestamp when the run was created
	CreatedAt time.Time `json:"createdAt"`
	// Whether the run is a destroy operation
	IsDestroy bool `json:"isDestroy"`
	// Whether the run has changes
	HasChanges bool `json:"hasChanges"`
	// Message associated with the run
	Message string `json:"message"`
	// Whether the run is a plan-only operation
	PlanOnly bool `json:"planOnly"`
	// Whether the run is a refresh operation
	Refresh bool `json:"refresh"`
	// Whether the run is a refresh-only operation
	RefreshOnly bool `json:"refreshOnly"`
	// Whether the run saves the plan
	SavePlan bool `json:"savePlan"`
	// Status of the run
	Status               string                `json:"status"`
	ConfigurationVersion *ConfigurationVersion `json:"configurationVersion,omitempty"`
}

func (r Run) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *Run) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *Run) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *Run) GetAutoApply() bool {
	if r == nil {
		return false
	}
	return r.AutoApply
}

func (r *Run) GetCreatedAt() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.CreatedAt
}

func (r *Run) GetIsDestroy() bool {
	if r == nil {
		return false
	}
	return r.IsDestroy
}

func (r *Run) GetHasChanges() bool {
	if r == nil {
		return false
	}
	return r.HasChanges
}

func (r *Run) GetMessage() string {
	if r == nil {
		return ""
	}
	return r.Message
}

func (r *Run) GetPlanOnly() bool {
	if r == nil {
		return false
	}
	return r.PlanOnly
}

func (r *Run) GetRefresh() bool {
	if r == nil {
		return false
	}
	return r.Refresh
}

func (r *Run) GetRefreshOnly() bool {
	if r == nil {
		return false
	}
	return r.RefreshOnly
}

func (r *Run) GetSavePlan() bool {
	if r == nil {
		return false
	}
	return r.SavePlan
}

func (r *Run) GetStatus() string {
	if r == nil {
		return ""
	}
	return r.Status
}

func (r *Run) GetConfigurationVersion() *ConfigurationVersion {
	if r == nil {
		return nil
	}
	return r.ConfigurationVersion
}
