// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RunResponse struct {
	Data Run `json:"data"`
}

func (r *RunResponse) GetData() Run {
	if r == nil {
		return Run{}
	}
	return r.Data
}
