// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RunResponse struct {
	Data Run `json:"data"`
}

func (o *RunResponse) GetData() Run {
	if o == nil {
		return Run{}
	}
	return o.Data
}
