// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 779f1f1f01f5

package components

type UpdateAppRequest struct {
	// Updated name for the app
	Name string `json:"name"`
}

func (u *UpdateAppRequest) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}
