// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2SchemaData struct {
	Chart        map[string]V2ChartSegment        `json:"chart,omitempty"`
	Transactions map[string]V2TransactionTemplate `json:"transactions,omitempty"`
}

func (v *V2SchemaData) GetChart() map[string]V2ChartSegment {
	if v == nil {
		return nil
	}
	return v.Chart
}

func (v *V2SchemaData) GetTransactions() map[string]V2TransactionTemplate {
	if v == nil {
		return nil
	}
	return v.Transactions
}
