// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d8e0b9428216

package components

type V2TransactionTemplate struct {
	Description *string `json:"description,omitempty"`
	Runtime     *string `json:"runtime,omitempty"`
	Script      *string `json:"script,omitempty"`
}

func (v *V2TransactionTemplate) GetDescription() *string {
	if v == nil {
		return nil
	}
	return v.Description
}

func (v *V2TransactionTemplate) GetRuntime() *string {
	if v == nil {
		return nil
	}
	return v.Runtime
}

func (v *V2TransactionTemplate) GetScript() *string {
	if v == nil {
		return nil
	}
	return v.Script
}
