// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// VariableDataCategory - Category of the variable
type VariableDataCategory string

const (
	VariableDataCategoryEnv       VariableDataCategory = "env"
	VariableDataCategoryTerraform VariableDataCategory = "terraform"
)

func (e VariableDataCategory) ToPointer() *VariableDataCategory {
	return &e
}
func (e *VariableDataCategory) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "env":
		fallthrough
	case "terraform":
		*e = VariableDataCategory(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VariableDataCategory: %v", v)
	}
}

type VariableData struct {
	// Key of the variable
	Key string `json:"key"`
	// Value of the variable
	Value string `json:"value"`
	// Description of the variable
	Description *string `json:"description,omitempty"`
	// Whether the variable is sensitive
	Sensitive bool `json:"sensitive"`
	// Category of the variable
	Category VariableDataCategory `json:"category"`
}

func (o *VariableData) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *VariableData) GetValue() string {
	if o == nil {
		return ""
	}
	return o.Value
}

func (o *VariableData) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *VariableData) GetSensitive() bool {
	if o == nil {
		return false
	}
	return o.Sensitive
}

func (o *VariableData) GetCategory() VariableDataCategory {
	if o == nil {
		return VariableDataCategory("")
	}
	return o.Category
}
