// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 221e26113be3

package components

type Variable struct {
	// Snake-case identifier (case-insensitive at the API boundary,
	// normalized to lowercase on storage to match `var.<name>` in the
	// generated HCL). Either `MONEYCORP_API_KEY` or
	// `moneycorp_api_key` is accepted.
	//
	Key string `json:"key"`
	// Value of the variable. Always treated as sensitive: `value` is
	// redacted (`REDACTED`) on every read endpoint.
	//
	Value string `json:"value"`
	// Description of the variable
	Description *string `json:"description,omitempty"`
	// Unique identifier for the variable
	ID string `json:"id"`
}

func (v *Variable) GetKey() string {
	if v == nil {
		return ""
	}
	return v.Key
}

func (v *Variable) GetValue() string {
	if v == nil {
		return ""
	}
	return v.Value
}

func (v *Variable) GetDescription() *string {
	if v == nil {
		return nil
	}
	return v.Description
}

func (v *Variable) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}
