// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Webhook struct {
	Endpoint string   `json:"endpoint"`
	Events   []string `json:"events,omitempty"`
	Name     string   `json:"name"`
	Secret   *string  `json:"secret,omitempty"`
}

func (w *Webhook) GetEndpoint() string {
	if w == nil {
		return ""
	}
	return w.Endpoint
}

func (w *Webhook) GetEvents() []string {
	if w == nil {
		return nil
	}
	return w.Events
}

func (w *Webhook) GetName() string {
	if w == nil {
		return ""
	}
	return w.Name
}

func (w *Webhook) GetSecret() *string {
	if w == nil {
		return nil
	}
	return w.Secret
}
