package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strconv"

	"github.com/formancehq/fctl/v4/internal/capabilities"
)

func main() {
	input := flag.String("input", "", "Path to OpenAPI JSON document")
	output := flag.String("output", "", "Path to generated Go manifest")
	flag.Parse()

	if *input == "" || *output == "" {
		fmt.Fprintln(os.Stderr, "usage: genmanifest -input generate.json -output manifest_generated.go")
		os.Exit(2)
	}

	file, err := os.Open(*input)
	if err != nil {
		fail("open input", err)
	}
	defer file.Close()

	manifest, err := capabilities.ParseOpenAPIManifest(file)
	if err != nil {
		fail("parse openapi", err)
	}

	data, err := renderGo(manifest)
	if err != nil {
		fail("render go", err)
	}
	if err := os.WriteFile(*output, data, 0o644); err != nil {
		fail("write output", err)
	}
}

func renderGo(manifest capabilities.Manifest) ([]byte, error) {
	buffer := bytes.Buffer{}
	buffer.WriteString("// Code generated by genmanifest; DO NOT EDIT.\n\n")
	buffer.WriteString("package capabilities\n\n")
	buffer.WriteString("var GeneratedManifest = Manifest{\n")
	fmt.Fprintf(&buffer, "\tSpecVersion: %s,\n", strconv.Quote(manifest.SpecVersion))
	buffer.WriteString("\tProducts: map[Product]ProductManifest{\n")

	products := make([]string, 0, len(manifest.Products))
	for product := range manifest.Products {
		products = append(products, string(product))
	}
	sort.Strings(products)

	for _, product := range products {
		productManifest := manifest.Products[capabilities.Product(product)]
		fmt.Fprintf(&buffer, "\t\tProduct(%s): {\n", strconv.Quote(product))
		buffer.WriteString("\t\t\tAPIVersions: []APIVersion{")
		for i, apiVersion := range productManifest.APIVersions {
			if i > 0 {
				buffer.WriteString(", ")
			}
			fmt.Fprintf(&buffer, "APIVersion(%s)", strconv.Quote(string(apiVersion)))
		}
		buffer.WriteString("},\n")
		buffer.WriteString("\t\t\tOperations: map[Feature]map[APIVersion]Operation{\n")

		features := make([]string, 0, len(productManifest.Operations))
		for feature := range productManifest.Operations {
			features = append(features, string(feature))
		}
		sort.Strings(features)

		for _, feature := range features {
			fmt.Fprintf(&buffer, "\t\t\t\tFeature(%s): {\n", strconv.Quote(feature))
			operations := productManifest.Operations[capabilities.Feature(feature)]
			apiVersions := make([]string, 0, len(operations))
			for apiVersion := range operations {
				apiVersions = append(apiVersions, string(apiVersion))
			}
			sort.Strings(apiVersions)
			for _, apiVersion := range apiVersions {
				operation := operations[capabilities.APIVersion(apiVersion)]
				fmt.Fprintf(&buffer, "\t\t\t\t\tAPIVersion(%s): {OperationID: %s, Method: %s, Path: %s",
					strconv.Quote(apiVersion),
					strconv.Quote(operation.OperationID),
					strconv.Quote(operation.Method),
					strconv.Quote(operation.Path),
				)
				if len(operation.Tags) > 0 {
					buffer.WriteString(", Tags: []string{")
					for i, tag := range operation.Tags {
						if i > 0 {
							buffer.WriteString(", ")
						}
						buffer.WriteString(strconv.Quote(tag))
					}
					buffer.WriteString("}")
				}
				buffer.WriteString("},\n")
			}
			buffer.WriteString("\t\t\t\t},\n")
		}

		buffer.WriteString("\t\t\t},\n")
		buffer.WriteString("\t\t},\n")
	}

	buffer.WriteString("\t},\n")
	buffer.WriteString("}\n")

	return format.Source(buffer.Bytes())
}

func fail(message string, err error) {
	fmt.Fprintf(os.Stderr, "%s: %v\n", message, err)
	os.Exit(1)
}
