// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 857d985e78ef

package operations

import (
	"github.com/formancehq/fctl/internal/deployserverclient/v3/models/components"
)

type AttachAppManifestRequest struct {
	ID                    string                           `pathParam:"style=simple,explode=false,name=id"`
	AttachManifestRequest components.AttachManifestRequest `request:"mediaType=application/json"`
}

func (a *AttachAppManifestRequest) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AttachAppManifestRequest) GetAttachManifestRequest() components.AttachManifestRequest {
	if a == nil {
		return components.AttachManifestRequest{}
	}
	return a.AttachManifestRequest
}

type AttachAppManifestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// manifestId missing or empty
	Error *components.Error
}

func (a *AttachAppManifestResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AttachAppManifestResponse) GetError() *components.Error {
	if a == nil {
		return nil
	}
	return a.Error
}
