// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7be33bfb9044

package operations

import (
	"github.com/formancehq/fctl/internal/deployserverclient/v3/models/components"
)

// CreateManifestRequestBody - JSON manifest content
type CreateManifestRequestBody struct {
}

type CreateManifestRequest struct {
	// Name for the manifest
	Name string `queryParam:"style=form,explode=true,name=name"`
	// Optional app ID to scope the manifest to a specific app
	AppID       *string                   `queryParam:"style=form,explode=true,name=appId"`
	RequestBody CreateManifestRequestBody `request:"mediaType=application/json"`
}

func (c *CreateManifestRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateManifestRequest) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

func (c *CreateManifestRequest) GetRequestBody() CreateManifestRequestBody {
	if c == nil {
		return CreateManifestRequestBody{}
	}
	return c.RequestBody
}

type CreateManifestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Manifest created successfully
	CreateManifestResponse *components.CreateManifestResponse
	// Error
	Error *components.Error
}

func (c *CreateManifestResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateManifestResponse) GetCreateManifestResponse() *components.CreateManifestResponse {
	if c == nil {
		return nil
	}
	return c.CreateManifestResponse
}

func (c *CreateManifestResponse) GetError() *components.Error {
	if c == nil {
		return nil
	}
	return c.Error
}
