// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/deployserverclient/models/components"
)

type CreateAppVariableRequest struct {
	ID                    string                           `pathParam:"style=simple,explode=false,name=id"`
	CreateVariableRequest components.CreateVariableRequest `request:"mediaType=application/json"`
}

func (o *CreateAppVariableRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateAppVariableRequest) GetCreateVariableRequest() components.CreateVariableRequest {
	if o == nil {
		return components.CreateVariableRequest{}
	}
	return o.CreateVariableRequest
}

type CreateAppVariableResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Variable created successfully
	CreateVariableResponse *components.CreateVariableResponse
	// Error
	Error *components.Error
}

func (o *CreateAppVariableResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateAppVariableResponse) GetCreateVariableResponse() *components.CreateVariableResponse {
	if o == nil {
		return nil
	}
	return o.CreateVariableResponse
}

func (o *CreateAppVariableResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
