// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/deployserverclient/models/components"
)

type DeleteAppVariableRequest struct {
	ID         string `pathParam:"style=simple,explode=false,name=id"`
	VariableID string `pathParam:"style=simple,explode=false,name=variableId"`
}

func (d *DeleteAppVariableRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DeleteAppVariableRequest) GetVariableID() string {
	if d == nil {
		return ""
	}
	return d.VariableID
}

type DeleteAppVariableResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	Error *components.Error
}

func (d *DeleteAppVariableResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteAppVariableResponse) GetError() *components.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
