// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/deployserverclient/models/components"
)

type DeleteAppVariableRequest struct {
	ID         string `pathParam:"style=simple,explode=false,name=id"`
	VariableID string `pathParam:"style=simple,explode=false,name=variableId"`
}

func (o *DeleteAppVariableRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *DeleteAppVariableRequest) GetVariableID() string {
	if o == nil {
		return ""
	}
	return o.VariableID
}

type DeleteAppVariableResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	Error *components.Error
}

func (o *DeleteAppVariableResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteAppVariableResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
