// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/deployserverclient/models/components"
)

type DeployAppConfigurationRequest struct {
	ID          string                 `pathParam:"style=simple,explode=false,name=id"`
	Application components.Application `request:"mediaType=application/json"`
}

func (o *DeployAppConfigurationRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *DeployAppConfigurationRequest) GetApplication() components.Application {
	if o == nil {
		return components.Application{}
	}
	return o.Application
}

type DeployAppConfigurationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// App configuration deployed successfully
	RunResponse *components.RunResponse
	// Error
	Error *components.Error
}

func (o *DeployAppConfigurationResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeployAppConfigurationResponse) GetRunResponse() *components.RunResponse {
	if o == nil {
		return nil
	}
	return o.RunResponse
}

func (o *DeployAppConfigurationResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
