// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: da484da15385

package operations

import (
	"github.com/formancehq/fctl/internal/deployserverclient/v3/models/components"
)

type DeployAppConfigurationRawRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	RequestBody any `request:"mediaType=application/yaml"`
}

func (d *DeployAppConfigurationRawRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DeployAppConfigurationRawRequest) GetRequestBody() any {
	if d == nil {
		return nil
	}
	return d.RequestBody
}

type DeployAppConfigurationRawResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// App configuration deployed successfully
	RunResponse *components.RunResponse
	// Error
	Error *components.Error
}

func (d *DeployAppConfigurationRawResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeployAppConfigurationRawResponse) GetRunResponse() *components.RunResponse {
	if d == nil {
		return nil
	}
	return d.RunResponse
}

func (d *DeployAppConfigurationRawResponse) GetError() *components.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
