// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/deployserverclient/models/components"
	"io"
)

type DownloadAppVersionRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DownloadAppVersionRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DownloadAppVersionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// App version downloaded successfully
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	ResponseStream io.ReadCloser
	// Error
	Error *components.Error
}

func (d *DownloadAppVersionResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DownloadAppVersionResponse) GetResponseStream() io.ReadCloser {
	if d == nil {
		return nil
	}
	return d.ResponseStream
}

func (d *DownloadAppVersionResponse) GetError() *components.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
