// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/deployserverclient/models/components"
)

type GetAppCurrentStateVersionRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetAppCurrentStateVersionRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetAppCurrentStateVersionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Current state version retrieved successfully
	Any any
	// Error
	Error *components.Error
}

func (o *GetAppCurrentStateVersionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetAppCurrentStateVersionResponse) GetAny() any {
	if o == nil {
		return nil
	}
	return o.Any
}

func (o *GetAppCurrentStateVersionResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
