// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/deployserverclient/models/components"
)

type GetCurrentAppVersionRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetCurrentAppVersionRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetCurrentAppVersionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Current app version retrieved successfully
	AppVersionResponse *components.AppVersionResponse
	// Error
	Error *components.Error
}

func (o *GetCurrentAppVersionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetCurrentAppVersionResponse) GetAppVersionResponse() *components.AppVersionResponse {
	if o == nil {
		return nil
	}
	return o.AppVersionResponse
}

func (o *GetCurrentAppVersionResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
