// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e8bf8a35a4b6

package operations

import (
	"github.com/formancehq/fctl/internal/deployserverclient/v3/models/components"
)

type ListManifestVersionsRequest struct {
	ManifestID string `pathParam:"style=simple,explode=false,name=manifestId"`
	// Maximum number of items to return on the first page. Capped at 100;
	// ignored when `cursor` is supplied (subsequent pages reuse the page
	// size baked into the cursor token). Defaults to 100.
	//
	PageSize *int64 `queryParam:"style=form,explode=true,name=pageSize"`
	// Opaque pagination token returned in `cursor.next` / `cursor.previous`
	// on the previous page. Pass it back unchanged to fetch the adjacent
	// page. Mutually exclusive with `pageSize` after the first request.
	//
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
}

func (l *ListManifestVersionsRequest) GetManifestID() string {
	if l == nil {
		return ""
	}
	return l.ManifestID
}

func (l *ListManifestVersionsRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

func (l *ListManifestVersionsRequest) GetCursor() *string {
	if l == nil {
		return nil
	}
	return l.Cursor
}

type ListManifestVersionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Manifest versions retrieved successfully
	ListManifestVersionsResponse *components.ListManifestVersionsResponse
	// Error
	Error *components.Error
}

func (l *ListManifestVersionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListManifestVersionsResponse) GetListManifestVersionsResponse() *components.ListManifestVersionsResponse {
	if l == nil {
		return nil
	}
	return l.ListManifestVersionsResponse
}

func (l *ListManifestVersionsResponse) GetError() *components.Error {
	if l == nil {
		return nil
	}
	return l.Error
}
