// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5836489f2f6f

package operations

import (
	"github.com/formancehq/fctl/v3/internal/deployserverclient/models/components"
)

type ListAppsRequest struct {
	OrganizationID string `queryParam:"style=form,explode=true,name=organizationId"`
	PageNumber     *int64 `queryParam:"style=form,explode=true,name=pageNumber"`
	PageSize       *int64 `queryParam:"style=form,explode=true,name=pageSize"`
}

func (l *ListAppsRequest) GetOrganizationID() string {
	if l == nil {
		return ""
	}
	return l.OrganizationID
}

func (l *ListAppsRequest) GetPageNumber() *int64 {
	if l == nil {
		return nil
	}
	return l.PageNumber
}

func (l *ListAppsRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

type ListAppsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Apps retrieved successfully
	ListAppsResponse *components.ListAppsResponse
	// Error
	Error *components.Error
}

func (l *ListAppsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListAppsResponse) GetListAppsResponse() *components.ListAppsResponse {
	if l == nil {
		return nil
	}
	return l.ListAppsResponse
}

func (l *ListAppsResponse) GetError() *components.Error {
	if l == nil {
		return nil
	}
	return l.Error
}
