// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a61642c0d316

package operations

import (
	"github.com/formancehq/fctl/v3/internal/deployserverclient/models/components"
)

type ReadAppRunsRequest struct {
	ID         string `pathParam:"style=simple,explode=false,name=id"`
	PageNumber *int64 `queryParam:"style=form,explode=true,name=pageNumber"`
	PageSize   *int64 `queryParam:"style=form,explode=true,name=pageSize"`
}

func (r *ReadAppRunsRequest) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *ReadAppRunsRequest) GetPageNumber() *int64 {
	if r == nil {
		return nil
	}
	return r.PageNumber
}

func (r *ReadAppRunsRequest) GetPageSize() *int64 {
	if r == nil {
		return nil
	}
	return r.PageSize
}

type ReadAppRunsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// App runs retrieved successfully
	ListRunsResponse *components.ListRunsResponse
	// Error
	Error *components.Error
}

func (r *ReadAppRunsResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *ReadAppRunsResponse) GetListRunsResponse() *components.ListRunsResponse {
	if r == nil {
		return nil
	}
	return r.ListRunsResponse
}

func (r *ReadAppRunsResponse) GetError() *components.Error {
	if r == nil {
		return nil
	}
	return r.Error
}
