// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/deployserverclient/models/components"
)

type ReadAppVariablesRequest struct {
	ID         string `pathParam:"style=simple,explode=false,name=id"`
	PageNumber *int64 `queryParam:"style=form,explode=true,name=pageNumber"`
	PageSize   *int64 `queryParam:"style=form,explode=true,name=pageSize"`
}

func (r *ReadAppVariablesRequest) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *ReadAppVariablesRequest) GetPageNumber() *int64 {
	if r == nil {
		return nil
	}
	return r.PageNumber
}

func (r *ReadAppVariablesRequest) GetPageSize() *int64 {
	if r == nil {
		return nil
	}
	return r.PageSize
}

type ReadAppVariablesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// App variables retrieved successfully
	ReadVariablesResponse *components.ReadVariablesResponse
	// Error
	Error *components.Error
}

func (r *ReadAppVariablesResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *ReadAppVariablesResponse) GetReadVariablesResponse() *components.ReadVariablesResponse {
	if r == nil {
		return nil
	}
	return r.ReadVariablesResponse
}

func (r *ReadAppVariablesResponse) GetError() *components.Error {
	if r == nil {
		return nil
	}
	return r.Error
}
