// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/deployserverclient/models/components"
)

type ReadAppVersionsRequest struct {
	ID         string `pathParam:"style=simple,explode=false,name=id"`
	PageNumber *int64 `queryParam:"style=form,explode=true,name=pageNumber"`
	PageSize   *int64 `queryParam:"style=form,explode=true,name=pageSize"`
}

func (o *ReadAppVersionsRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ReadAppVersionsRequest) GetPageNumber() *int64 {
	if o == nil {
		return nil
	}
	return o.PageNumber
}

func (o *ReadAppVersionsRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

type ReadAppVersionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// App versions retrieved successfully
	ListVersionsResponse *components.ListVersionsResponse
	// Error
	Error *components.Error
}

func (o *ReadAppVersionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ReadAppVersionsResponse) GetListVersionsResponse() *components.ListVersionsResponse {
	if o == nil {
		return nil
	}
	return o.ListVersionsResponse
}

func (o *ReadAppVersionsResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
