// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b72515ab4199

package operations

import (
	"github.com/formancehq/fctl/internal/deployserverclient/v3/models/components"
)

type ReadDeploymentLogsRequest struct {
	DeploymentID string `pathParam:"style=simple,explode=false,name=deploymentId"`
}

func (r *ReadDeploymentLogsRequest) GetDeploymentID() string {
	if r == nil {
		return ""
	}
	return r.DeploymentID
}

type ReadDeploymentLogsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Deployment logs retrieved successfully
	ReadLogsResponse *components.ReadLogsResponse
	// Error
	Error *components.Error
}

func (r *ReadDeploymentLogsResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *ReadDeploymentLogsResponse) GetReadLogsResponse() *components.ReadLogsResponse {
	if r == nil {
		return nil
	}
	return r.ReadLogsResponse
}

func (r *ReadDeploymentLogsResponse) GetError() *components.Error {
	if r == nil {
		return nil
	}
	return r.Error
}
