// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: bde8c9da719b

package operations

import (
	"github.com/formancehq/fctl/v3/internal/deployserverclient/models/components"
)

type ReadCurrentRunLogsRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (r *ReadCurrentRunLogsRequest) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

type ReadCurrentRunLogsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Current run logs retrieved successfully
	ReadLogsResponse *components.ReadLogsResponse
	// Error
	Error *components.Error
}

func (r *ReadCurrentRunLogsResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *ReadCurrentRunLogsResponse) GetReadLogsResponse() *components.ReadLogsResponse {
	if r == nil {
		return nil
	}
	return r.ReadLogsResponse
}

func (r *ReadCurrentRunLogsResponse) GetError() *components.Error {
	if r == nil {
		return nil
	}
	return r.Error
}
