// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 2236f4e2f610

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/formancehq/fctl/v3/internal/deployserverclient/models/components"
	"io"
)

type From string

const (
	FromState From = "state"
)

func (e From) ToPointer() *From {
	return &e
}
func (e *From) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "state":
		*e = From(v)
		return nil
	default:
		return fmt.Errorf("invalid value for From: %v", v)
	}
}

type ReadCurrentAppVersionRequest struct {
	ID   string `pathParam:"style=simple,explode=false,name=id"`
	From *From  `queryParam:"style=form,explode=true,name=from"`
}

func (r *ReadCurrentAppVersionRequest) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *ReadCurrentAppVersionRequest) GetFrom() *From {
	if r == nil {
		return nil
	}
	return r.From
}

type ReadCurrentAppVersionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Current app version retrieved successfully
	AppVersionResponse *components.AppVersionResponse
	// Current app version retrieved successfully
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	TwoHundredApplicationGzipResponseStream io.ReadCloser
	// Current app version retrieved successfully
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	TwoHundredApplicationYamlResponseStream io.ReadCloser
	// Error
	Error *components.Error
}

func (r *ReadCurrentAppVersionResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *ReadCurrentAppVersionResponse) GetAppVersionResponse() *components.AppVersionResponse {
	if r == nil {
		return nil
	}
	return r.AppVersionResponse
}

func (r *ReadCurrentAppVersionResponse) GetTwoHundredApplicationGzipResponseStream() io.ReadCloser {
	if r == nil {
		return nil
	}
	return r.TwoHundredApplicationGzipResponseStream
}

func (r *ReadCurrentAppVersionResponse) GetTwoHundredApplicationYamlResponseStream() io.ReadCloser {
	if r == nil {
		return nil
	}
	return r.TwoHundredApplicationYamlResponseStream
}

func (r *ReadCurrentAppVersionResponse) GetError() *components.Error {
	if r == nil {
		return nil
	}
	return r.Error
}
