// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/deployserverclient/models/components"
)

type ReadAppVariablesRequest struct {
	ID         string `pathParam:"style=simple,explode=false,name=id"`
	PageNumber *int64 `queryParam:"style=form,explode=true,name=pageNumber"`
	PageSize   *int64 `queryParam:"style=form,explode=true,name=pageSize"`
}

func (o *ReadAppVariablesRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ReadAppVariablesRequest) GetPageNumber() *int64 {
	if o == nil {
		return nil
	}
	return o.PageNumber
}

func (o *ReadAppVariablesRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

type ReadAppVariablesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// App variables retrieved successfully
	ReadVariablesResponse *components.ReadVariablesResponse
	// Error
	Error *components.Error
}

func (o *ReadAppVariablesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ReadAppVariablesResponse) GetReadVariablesResponse() *components.ReadVariablesResponse {
	if o == nil {
		return nil
	}
	return o.ReadVariablesResponse
}

func (o *ReadAppVariablesResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
