// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/deployserverclient/models/components"
)

type ReadVersionRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *ReadVersionRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type ReadVersionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// version retrieved successfully
	AppVersionResponse *components.AppVersionResponse
	// Error
	Error *components.Error
}

func (o *ReadVersionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ReadVersionResponse) GetAppVersionResponse() *components.AppVersionResponse {
	if o == nil {
		return nil
	}
	return o.AppVersionResponse
}

func (o *ReadVersionResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
