// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/deployserverclient/models/components"
)

type ReadCurrentRunRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *ReadCurrentRunRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type ReadCurrentRunResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Current run retrieved successfully
	RunResponse *components.RunResponse
	// Error
	Error *components.Error
}

func (o *ReadCurrentRunResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ReadCurrentRunResponse) GetRunResponse() *components.RunResponse {
	if o == nil {
		return nil
	}
	return o.RunResponse
}

func (o *ReadCurrentRunResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
