// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ae784249b40f

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/formancehq/fctl/internal/deployserverclient/v3/models/components"
	"io"
)

type ReadDeploymentInclude string

const (
	ReadDeploymentIncludeState ReadDeploymentInclude = "state"
)

func (e ReadDeploymentInclude) ToPointer() *ReadDeploymentInclude {
	return &e
}
func (e *ReadDeploymentInclude) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "state":
		*e = ReadDeploymentInclude(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ReadDeploymentInclude: %v", v)
	}
}

type ReadDeploymentRequest struct {
	DeploymentID string `pathParam:"style=simple,explode=false,name=deploymentId"`
	// Comma-separated list of related resources to include.
	// - `state`: Include the Terraform state produced by this deployment's run.
	//
	Include []ReadDeploymentInclude `queryParam:"style=form,explode=true,name=include"`
}

func (r *ReadDeploymentRequest) GetDeploymentID() string {
	if r == nil {
		return ""
	}
	return r.DeploymentID
}

func (r *ReadDeploymentRequest) GetInclude() []ReadDeploymentInclude {
	if r == nil {
		return nil
	}
	return r.Include
}

type ReadDeploymentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Deployment retrieved successfully
	DeploymentResponse *components.DeploymentResponse
	// Deployment retrieved successfully
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	TwoHundredApplicationGzipResponseStream io.ReadCloser
	// Deployment retrieved successfully
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	TwoHundredApplicationYamlResponseStream io.ReadCloser
	// Error
	Error *components.Error
}

func (r *ReadDeploymentResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *ReadDeploymentResponse) GetDeploymentResponse() *components.DeploymentResponse {
	if r == nil {
		return nil
	}
	return r.DeploymentResponse
}

func (r *ReadDeploymentResponse) GetTwoHundredApplicationGzipResponseStream() io.ReadCloser {
	if r == nil {
		return nil
	}
	return r.TwoHundredApplicationGzipResponseStream
}

func (r *ReadDeploymentResponse) GetTwoHundredApplicationYamlResponseStream() io.ReadCloser {
	if r == nil {
		return nil
	}
	return r.TwoHundredApplicationYamlResponseStream
}

func (r *ReadDeploymentResponse) GetError() *components.Error {
	if r == nil {
		return nil
	}
	return r.Error
}
