// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5a5e3776c473

package operations

import (
	"github.com/formancehq/fctl/internal/deployserverclient/v3/models/components"
)

type UpdateManifestRequest struct {
	ManifestID            string                           `pathParam:"style=simple,explode=false,name=manifestId"`
	UpdateManifestRequest components.UpdateManifestRequest `request:"mediaType=application/json"`
}

func (u *UpdateManifestRequest) GetManifestID() string {
	if u == nil {
		return ""
	}
	return u.ManifestID
}

func (u *UpdateManifestRequest) GetUpdateManifestRequest() components.UpdateManifestRequest {
	if u == nil {
		return components.UpdateManifestRequest{}
	}
	return u.UpdateManifestRequest
}

type UpdateManifestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Manifest updated successfully
	ManifestResponse *components.ManifestResponse
	// Error
	Error *components.Error
}

func (u *UpdateManifestResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateManifestResponse) GetManifestResponse() *components.ManifestResponse {
	if u == nil {
		return nil
	}
	return u.ManifestResponse
}

func (u *UpdateManifestResponse) GetError() *components.Error {
	if u == nil {
		return nil
	}
	return u.Error
}
