// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/fctl/internal/deployserverclient/models/components"
)

type UpdateAppRequest struct {
	ID               string                      `pathParam:"style=simple,explode=false,name=id"`
	UpdateAppRequest components.UpdateAppRequest `request:"mediaType=application/json"`
}

func (o *UpdateAppRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateAppRequest) GetUpdateAppRequest() components.UpdateAppRequest {
	if o == nil {
		return components.UpdateAppRequest{}
	}
	return o.UpdateAppRequest
}

type UpdateAppResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	Error *components.Error
}

func (o *UpdateAppResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateAppResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
