package auth

import (
	"strings"

	"github.com/formancehq/fctl/pkg/pluginsdk"
)

// Inputs belong to leaves. The host resolves stack context and runs these
// ordinary read commands through the plugin's injected client.
func addInputs(command *pluginsdk.CommandSpec, parent []string) {
	path := append(append([]string{}, parent...), pluginsdk.CommandName(*command))
	if command.Runnable {
		command.Inputs = commandInputs(strings.Join(path, " "))
	}
	for i := range command.Subcommands {
		addInputs(&command.Subcommands[i], path)
	}
}

func commandInputs(path string) []pluginsdk.InputSpec {
	switch path {
	case "auth clients create":
		return clientCreateInputs()
	case "auth clients show", "auth clients delete", "auth clients secrets list":
		return []pluginsdk.InputSpec{clientInput()}
	case "auth clients update":
		// Do not add default booleans, arrays or objects to an update patch.
		// Existing options are merged by updateClient. Explicit --data patches
		// also let callers update any option without requiring a new name.
		return []pluginsdk.InputSpec{
			clientInput(),
			{Title: "Client name", Description: "New name for the client", Kind: "input", BodyPointer: "/name", ValueType: "string", Required: true},
			{Title: "Description", Description: "Leave blank to preserve the current description", Kind: "input", BodyPointer: "/description", ValueType: "string"},
		}
	case "auth clients secrets create":
		return []pluginsdk.InputSpec{
			clientInput(),
			{Title: "Secret name", Description: "Label for the new secret; its clear value is generated by Auth", Kind: "input", BodyPointer: "/name", ValueType: "string", Required: true},
			{Title: "Metadata", Description: `Optional JSON object of string values, e.g. {"purpose":"ci"}`, Kind: "text", BodyPointer: "/metadata", ValueType: "json"},
		}
	case "auth clients secrets delete":
		return []pluginsdk.InputSpec{
			clientInput(),
			{Title: "Client secret", Kind: "select", Argument: new(1), ValueType: "string", Required: true,
				Source: &pluginsdk.ChoiceSource{CommandPath: []string{"auth", "clients", "secrets", "list"}, Args: []string{"$arg0"}, ValueField: "id", LabelFields: []string{"name", "id"}, EmptyMessage: "This client has no secrets to delete"}},
		}
	case "auth users show":
		return []pluginsdk.InputSpec{
			{Title: "User", Kind: "select", Argument: new(0), ValueType: "string", Required: true,
				Source: &pluginsdk.ChoiceSource{CommandPath: []string{"auth", "users", "list"}, ValueField: "id", LabelFields: []string{"email", "subject", "id"}, EmptyMessage: "No Auth users are available"}},
		}
	default:
		return nil
	}
}

func clientInput() pluginsdk.InputSpec {
	return pluginsdk.InputSpec{Title: "OAuth2 client", Kind: "select", Argument: new(0), ValueType: "string", Required: true,
		Source: &pluginsdk.ChoiceSource{CommandPath: []string{"auth", "clients", "list"}, ValueField: "id", LabelFields: []string{"name", "id"}, EmptyMessage: "No OAuth2 clients are available; create a client first"}}
}

func clientCreateInputs() []pluginsdk.InputSpec {
	return []pluginsdk.InputSpec{
		{Title: "Client name", Kind: "input", BodyPointer: "/name", ValueType: "string", Required: true},
		{Title: "Description", Kind: "input", BodyPointer: "/description", ValueType: "string"},
		{Title: "Public client", Description: "Public clients cannot keep a client secret", Kind: "confirm", BodyPointer: "/public", ValueType: "bool", Default: "false"},
		{Title: "Trusted client", Description: "Trusted clients bypass user consent", Kind: "confirm", BodyPointer: "/trusted", ValueType: "bool", Default: "false"},
		{Title: "Scopes", Description: `JSON array of scope strings, e.g. ["ledger:read"]`, Kind: "text", BodyPointer: "/scopes", ValueType: "json"},
		{Title: "Redirect URIs", Description: `JSON array of URI strings, e.g. ["https://example.test/callback"]`, Kind: "text", BodyPointer: "/redirectUris", ValueType: "json"},
		{Title: "Post-logout redirect URIs", Description: "Optional JSON array of URI strings", Kind: "text", BodyPointer: "/postLogoutRedirectUris", ValueType: "json"},
		{Title: "Metadata", Description: `Optional JSON object of string values, e.g. {"purpose":"automation"}`, Kind: "text", BodyPointer: "/metadata", ValueType: "json"},
	}
}
