workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Terraform HCP Proxy API:
        inputs:
            - location: ../../openapi/deployserver.yaml
        registry:
            location: registry.speakeasyapi.dev/formance/formance/terraform-hcp-proxy-api
targets:
    deploy-server:
        target: go
        source: Terraform HCP Proxy API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/formance/formance/terraform-hcp-proxy-api-go-code-samples
            labelOverride:
                fixedValue: Go (SDK)
            blocking: false
