// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Action string

const (
	ActionAgentsConnected           Action = "agents.connected"
	ActionAgentsDisconnected        Action = "agents.disconnected"
	ActionInvitationsCreated        Action = "invitations.created"
	ActionInvitationsAccepted       Action = "invitations.accepted"
	ActionInvitationsRejected       Action = "invitations.rejected"
	ActionInvitationsCancelled      Action = "invitations.cancelled"
	ActionOrganizationsCreated      Action = "organizations.created"
	ActionOrganizationsUpdated      Action = "organizations.updated"
	ActionOrganizationsDeleted      Action = "organizations.deleted"
	ActionOrganizationsUserDeleted  Action = "organizations.user.deleted"
	ActionOrganizationsUserUpdated  Action = "organizations.user.updated"
	ActionRegionsCreated            Action = "regions.created"
	ActionRegionsDeleted            Action = "regions.deleted"
	ActionUsersCreated              Action = "users.created"
	ActionUsersDeleted              Action = "users.deleted"
	ActionStacksDisposal            Action = "stacks.disposal"
	ActionStacksDisposalReset       Action = "stacks.disposal-reset"
	ActionStacksWarned              Action = "stacks.warned"
	ActionStacksPruned              Action = "stacks.pruned"
	ActionStacksStatusUpdated       Action = "stacks.status.updated"
	ActionStacksCreated             Action = "stacks.created"
	ActionStacksUpdated             Action = "stacks.updated"
	ActionStacksDeleted             Action = "stacks.deleted"
	ActionStacksRestored            Action = "stacks.restored"
	ActionStacksDisabled            Action = "stacks.disabled"
	ActionStacksEnabled             Action = "stacks.enabled"
	ActionStacksUpgraded            Action = "stacks.upgraded"
	ActionStacksStargateEnabled     Action = "stacks.stargate.enabled"
	ActionStacksStargateDisabled    Action = "stacks.stargate.disabled"
	ActionStacksUserUpdated         Action = "stacks.user.updated"
	ActionStacksUserDeleted         Action = "stacks.user.deleted"
	ActionStacksReachnessUpdated    Action = "stacks.reachness.updated"
	ActionStacksModuleEnabled       Action = "stacks.module.enabled"
	ActionStacksModuleDisabled      Action = "stacks.module.disabled"
	ActionStacksModuleStatusUpdated Action = "stacks.module.status.updated"
	ActionPoliciesCreated           Action = "policies.created"
	ActionPoliciesUpdated           Action = "policies.updated"
	ActionPoliciesDeleted           Action = "policies.deleted"
	ActionPoliciesScopeAdded        Action = "policies.scope.added"
	ActionPoliciesScopeRemoved      Action = "policies.scope.removed"
)

func (e Action) ToPointer() *Action {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Action) IsExact() bool {
	if e != nil {
		switch *e {
		case "agents.connected", "agents.disconnected", "invitations.created", "invitations.accepted", "invitations.rejected", "invitations.cancelled", "organizations.created", "organizations.updated", "organizations.deleted", "organizations.user.deleted", "organizations.user.updated", "regions.created", "regions.deleted", "users.created", "users.deleted", "stacks.disposal", "stacks.disposal-reset", "stacks.warned", "stacks.pruned", "stacks.status.updated", "stacks.created", "stacks.updated", "stacks.deleted", "stacks.restored", "stacks.disabled", "stacks.enabled", "stacks.upgraded", "stacks.stargate.enabled", "stacks.stargate.disabled", "stacks.user.updated", "stacks.user.deleted", "stacks.reachness.updated", "stacks.module.enabled", "stacks.module.disabled", "stacks.module.status.updated", "policies.created", "policies.updated", "policies.deleted", "policies.scope.added", "policies.scope.removed":
			return true
		}
	}
	return false
}
