// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type Action string

const (
	ActionAgentsConnected           Action = "agents.connected"
	ActionAgentsDisconnected        Action = "agents.disconnected"
	ActionInvitationsCreated        Action = "invitations.created"
	ActionInvitationsAccepted       Action = "invitations.accepted"
	ActionInvitationsRejected       Action = "invitations.rejected"
	ActionInvitationsCancelled      Action = "invitations.cancelled"
	ActionOrganizationsCreated      Action = "organizations.created"
	ActionOrganizationsUpdated      Action = "organizations.updated"
	ActionOrganizationsDeleted      Action = "organizations.deleted"
	ActionOrganizationsUserDeleted  Action = "organizations.user.deleted"
	ActionOrganizationsUserUpdated  Action = "organizations.user.updated"
	ActionRegionsCreated            Action = "regions.created"
	ActionRegionsDeleted            Action = "regions.deleted"
	ActionUsersCreated              Action = "users.created"
	ActionUsersDeleted              Action = "users.deleted"
	ActionStacksDisposal            Action = "stacks.disposal"
	ActionStacksDisposalReset       Action = "stacks.disposal-reset"
	ActionStacksWarned              Action = "stacks.warned"
	ActionStacksPruned              Action = "stacks.pruned"
	ActionStacksStatusUpdated       Action = "stacks.status.updated"
	ActionStacksCreated             Action = "stacks.created"
	ActionStacksUpdated             Action = "stacks.updated"
	ActionStacksDeleted             Action = "stacks.deleted"
	ActionStacksRestored            Action = "stacks.restored"
	ActionStacksDisabled            Action = "stacks.disabled"
	ActionStacksEnabled             Action = "stacks.enabled"
	ActionStacksUpgraded            Action = "stacks.upgraded"
	ActionStacksStargateEnabled     Action = "stacks.stargate.enabled"
	ActionStacksStargateDisabled    Action = "stacks.stargate.disabled"
	ActionStacksUserUpdated         Action = "stacks.user.updated"
	ActionStacksUserDeleted         Action = "stacks.user.deleted"
	ActionStacksReachnessUpdated    Action = "stacks.reachness.updated"
	ActionStacksModuleEnabled       Action = "stacks.module.enabled"
	ActionStacksModuleDisabled      Action = "stacks.module.disabled"
	ActionStacksModuleStatusUpdated Action = "stacks.module.status.updated"
	ActionPoliciesCreated           Action = "policies.created"
	ActionPoliciesUpdated           Action = "policies.updated"
	ActionPoliciesDeleted           Action = "policies.deleted"
	ActionPoliciesScopeAdded        Action = "policies.scope.added"
	ActionPoliciesScopeRemoved      Action = "policies.scope.removed"
)

func (e Action) ToPointer() *Action {
	return &e
}
func (e *Action) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "agents.connected":
		fallthrough
	case "agents.disconnected":
		fallthrough
	case "invitations.created":
		fallthrough
	case "invitations.accepted":
		fallthrough
	case "invitations.rejected":
		fallthrough
	case "invitations.cancelled":
		fallthrough
	case "organizations.created":
		fallthrough
	case "organizations.updated":
		fallthrough
	case "organizations.deleted":
		fallthrough
	case "organizations.user.deleted":
		fallthrough
	case "organizations.user.updated":
		fallthrough
	case "regions.created":
		fallthrough
	case "regions.deleted":
		fallthrough
	case "users.created":
		fallthrough
	case "users.deleted":
		fallthrough
	case "stacks.disposal":
		fallthrough
	case "stacks.disposal-reset":
		fallthrough
	case "stacks.warned":
		fallthrough
	case "stacks.pruned":
		fallthrough
	case "stacks.status.updated":
		fallthrough
	case "stacks.created":
		fallthrough
	case "stacks.updated":
		fallthrough
	case "stacks.deleted":
		fallthrough
	case "stacks.restored":
		fallthrough
	case "stacks.disabled":
		fallthrough
	case "stacks.enabled":
		fallthrough
	case "stacks.upgraded":
		fallthrough
	case "stacks.stargate.enabled":
		fallthrough
	case "stacks.stargate.disabled":
		fallthrough
	case "stacks.user.updated":
		fallthrough
	case "stacks.user.deleted":
		fallthrough
	case "stacks.reachness.updated":
		fallthrough
	case "stacks.module.enabled":
		fallthrough
	case "stacks.module.disabled":
		fallthrough
	case "stacks.module.status.updated":
		fallthrough
	case "policies.created":
		fallthrough
	case "policies.updated":
		fallthrough
	case "policies.deleted":
		fallthrough
	case "policies.scope.added":
		fallthrough
	case "policies.scope.removed":
		*e = Action(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Action: %v", v)
	}
}
