// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/fctl/internal/membershipclient/internal/utils"
	"time"
)

type AnyRegion struct {
	ID             string               `json:"id"`
	BaseURL        string               `json:"baseUrl"`
	CreatedAt      string               `json:"createdAt"`
	Active         bool                 `json:"active"`
	LastPing       *time.Time           `json:"lastPing,omitzero"`
	Name           string               `json:"name"`
	Capabilities   RegionCapability     `json:"capabilities"`
	AgentID        string               `json:"agentID"`
	Outdated       bool                 `json:"outdated"`
	CreatorID      *string              `json:"creatorId,omitzero"`
	Version        *string              `json:"version,omitzero"`
	ClientID       *string              `json:"clientID,omitzero"`
	OrganizationID *string              `json:"organizationID,omitzero"`
	Creator        *User                `json:"creator,omitzero"`
	Production     *bool                `json:"production,omitzero"`
	Public         bool                 `json:"public"`
	Secret         *PrivateRegionSecret `json:"secret,omitzero"`
}

func (a AnyRegion) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AnyRegion) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AnyRegion) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AnyRegion) GetBaseURL() string {
	if a == nil {
		return ""
	}
	return a.BaseURL
}

func (a *AnyRegion) GetCreatedAt() string {
	if a == nil {
		return ""
	}
	return a.CreatedAt
}

func (a *AnyRegion) GetActive() bool {
	if a == nil {
		return false
	}
	return a.Active
}

func (a *AnyRegion) GetLastPing() *time.Time {
	if a == nil {
		return nil
	}
	return a.LastPing
}

func (a *AnyRegion) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AnyRegion) GetCapabilities() RegionCapability {
	if a == nil {
		return RegionCapability{}
	}
	return a.Capabilities
}

func (a *AnyRegion) GetAgentID() string {
	if a == nil {
		return ""
	}
	return a.AgentID
}

func (a *AnyRegion) GetOutdated() bool {
	if a == nil {
		return false
	}
	return a.Outdated
}

func (a *AnyRegion) GetCreatorID() *string {
	if a == nil {
		return nil
	}
	return a.CreatorID
}

func (a *AnyRegion) GetVersion() *string {
	if a == nil {
		return nil
	}
	return a.Version
}

func (a *AnyRegion) GetClientID() *string {
	if a == nil {
		return nil
	}
	return a.ClientID
}

func (a *AnyRegion) GetOrganizationID() *string {
	if a == nil {
		return nil
	}
	return a.OrganizationID
}

func (a *AnyRegion) GetCreator() *User {
	if a == nil {
		return nil
	}
	return a.Creator
}

func (a *AnyRegion) GetProduction() *bool {
	if a == nil {
		return nil
	}
	return a.Production
}

func (a *AnyRegion) GetPublic() bool {
	if a == nil {
		return false
	}
	return a.Public
}

func (a *AnyRegion) GetSecret() *PrivateRegionSecret {
	if a == nil {
		return nil
	}
	return a.Secret
}
