// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/fctl/internal/membershipclient/internal/utils"
	"time"
)

type ApplicationWithScope struct {
	// Application name
	Name string `json:"name"`
	// Application description
	Description *string `json:"description,omitzero"`
	// Application URL (must be unique)
	URL string `json:"url"`
	// Application alias
	Alias string `json:"alias"`
	// Application ID
	ID string `json:"id"`
	// Creation date
	CreatedAt time.Time `json:"createdAt"`
	// Last update date
	UpdatedAt time.Time `json:"updatedAt"`
	// List of scopes associated with this application
	Scopes []Scope `json:"scopes"`
}

func (a ApplicationWithScope) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ApplicationWithScope) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"name", "url", "alias", "id", "createdAt", "updatedAt", "scopes"}); err != nil {
		return err
	}
	return nil
}

func (a *ApplicationWithScope) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *ApplicationWithScope) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *ApplicationWithScope) GetURL() string {
	if a == nil {
		return ""
	}
	return a.URL
}

func (a *ApplicationWithScope) GetAlias() string {
	if a == nil {
		return ""
	}
	return a.Alias
}

func (a *ApplicationWithScope) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *ApplicationWithScope) GetCreatedAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.CreatedAt
}

func (a *ApplicationWithScope) GetUpdatedAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.UpdatedAt
}

func (a *ApplicationWithScope) GetScopes() []Scope {
	if a == nil {
		return []Scope{}
	}
	return a.Scopes
}
