// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/formancehq/fctl/internal/membershipclient/internal/utils"
)

// AuthenticationProviderDataOIDCConfigType - Type of the authentication provider
type AuthenticationProviderDataOIDCConfigType string

const (
	AuthenticationProviderDataOIDCConfigTypeOidc      AuthenticationProviderDataOIDCConfigType = "oidc"
	AuthenticationProviderDataOIDCConfigTypeGoogle    AuthenticationProviderDataOIDCConfigType = "google"
	AuthenticationProviderDataOIDCConfigTypeGithub    AuthenticationProviderDataOIDCConfigType = "github"
	AuthenticationProviderDataOIDCConfigTypeMicrosoft AuthenticationProviderDataOIDCConfigType = "microsoft"
)

func (e AuthenticationProviderDataOIDCConfigType) ToPointer() *AuthenticationProviderDataOIDCConfigType {
	return &e
}
func (e *AuthenticationProviderDataOIDCConfigType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "oidc":
		fallthrough
	case "google":
		fallthrough
	case "github":
		fallthrough
	case "microsoft":
		*e = AuthenticationProviderDataOIDCConfigType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AuthenticationProviderDataOIDCConfigType: %v", v)
	}
}

type AuthenticationProviderDataOIDCConfigConfig struct {
	// OIDC issuer URL
	Issuer        string  `json:"issuer"`
	DiscoveryPath *string `default:"/.well-known/openid-configuration" json:"discoveryPath"`
}

func (a AuthenticationProviderDataOIDCConfigConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthenticationProviderDataOIDCConfigConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuthenticationProviderDataOIDCConfigConfig) GetIssuer() string {
	if a == nil {
		return ""
	}
	return a.Issuer
}

func (a *AuthenticationProviderDataOIDCConfigConfig) GetDiscoveryPath() *string {
	if a == nil {
		return nil
	}
	return a.DiscoveryPath
}

type AuthenticationProviderDataOIDCConfig struct {
	// Type of the authentication provider
	Type AuthenticationProviderDataOIDCConfigType `json:"type"`
	// Name of the authentication provider
	Name string `json:"name"`
	// Client ID for the authentication provider
	ClientID string `json:"clientID"`
	// Client secret for the authentication provider
	ClientSecret string                                     `json:"clientSecret"`
	Config       AuthenticationProviderDataOIDCConfigConfig `json:"config"`
}

func (a AuthenticationProviderDataOIDCConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthenticationProviderDataOIDCConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuthenticationProviderDataOIDCConfig) GetType() AuthenticationProviderDataOIDCConfigType {
	if a == nil {
		return AuthenticationProviderDataOIDCConfigType("")
	}
	return a.Type
}

func (a *AuthenticationProviderDataOIDCConfig) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AuthenticationProviderDataOIDCConfig) GetClientID() string {
	if a == nil {
		return ""
	}
	return a.ClientID
}

func (a *AuthenticationProviderDataOIDCConfig) GetClientSecret() string {
	if a == nil {
		return ""
	}
	return a.ClientSecret
}

func (a *AuthenticationProviderDataOIDCConfig) GetConfig() AuthenticationProviderDataOIDCConfigConfig {
	if a == nil {
		return AuthenticationProviderDataOIDCConfigConfig{}
	}
	return a.Config
}

// AuthenticationProviderDataGithubIDPConfigType - Type of the authentication provider
type AuthenticationProviderDataGithubIDPConfigType string

const (
	AuthenticationProviderDataGithubIDPConfigTypeOidc      AuthenticationProviderDataGithubIDPConfigType = "oidc"
	AuthenticationProviderDataGithubIDPConfigTypeGoogle    AuthenticationProviderDataGithubIDPConfigType = "google"
	AuthenticationProviderDataGithubIDPConfigTypeGithub    AuthenticationProviderDataGithubIDPConfigType = "github"
	AuthenticationProviderDataGithubIDPConfigTypeMicrosoft AuthenticationProviderDataGithubIDPConfigType = "microsoft"
)

func (e AuthenticationProviderDataGithubIDPConfigType) ToPointer() *AuthenticationProviderDataGithubIDPConfigType {
	return &e
}
func (e *AuthenticationProviderDataGithubIDPConfigType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "oidc":
		fallthrough
	case "google":
		fallthrough
	case "github":
		fallthrough
	case "microsoft":
		*e = AuthenticationProviderDataGithubIDPConfigType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AuthenticationProviderDataGithubIDPConfigType: %v", v)
	}
}

type AuthenticationProviderDataGithubIDPConfigConfig struct {
}

func (a AuthenticationProviderDataGithubIDPConfigConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthenticationProviderDataGithubIDPConfigConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

type AuthenticationProviderDataGithubIDPConfig struct {
	// Type of the authentication provider
	Type AuthenticationProviderDataGithubIDPConfigType `json:"type"`
	// Name of the authentication provider
	Name string `json:"name"`
	// Client ID for the authentication provider
	ClientID string `json:"clientID"`
	// Client secret for the authentication provider
	ClientSecret string                                          `json:"clientSecret"`
	Config       AuthenticationProviderDataGithubIDPConfigConfig `json:"config"`
}

func (a AuthenticationProviderDataGithubIDPConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthenticationProviderDataGithubIDPConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuthenticationProviderDataGithubIDPConfig) GetType() AuthenticationProviderDataGithubIDPConfigType {
	if a == nil {
		return AuthenticationProviderDataGithubIDPConfigType("")
	}
	return a.Type
}

func (a *AuthenticationProviderDataGithubIDPConfig) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AuthenticationProviderDataGithubIDPConfig) GetClientID() string {
	if a == nil {
		return ""
	}
	return a.ClientID
}

func (a *AuthenticationProviderDataGithubIDPConfig) GetClientSecret() string {
	if a == nil {
		return ""
	}
	return a.ClientSecret
}

func (a *AuthenticationProviderDataGithubIDPConfig) GetConfig() AuthenticationProviderDataGithubIDPConfigConfig {
	if a == nil {
		return AuthenticationProviderDataGithubIDPConfigConfig{}
	}
	return a.Config
}

// AuthenticationProviderDataMicrosoftIDPConfigType - Type of the authentication provider
type AuthenticationProviderDataMicrosoftIDPConfigType string

const (
	AuthenticationProviderDataMicrosoftIDPConfigTypeOidc      AuthenticationProviderDataMicrosoftIDPConfigType = "oidc"
	AuthenticationProviderDataMicrosoftIDPConfigTypeGoogle    AuthenticationProviderDataMicrosoftIDPConfigType = "google"
	AuthenticationProviderDataMicrosoftIDPConfigTypeGithub    AuthenticationProviderDataMicrosoftIDPConfigType = "github"
	AuthenticationProviderDataMicrosoftIDPConfigTypeMicrosoft AuthenticationProviderDataMicrosoftIDPConfigType = "microsoft"
)

func (e AuthenticationProviderDataMicrosoftIDPConfigType) ToPointer() *AuthenticationProviderDataMicrosoftIDPConfigType {
	return &e
}
func (e *AuthenticationProviderDataMicrosoftIDPConfigType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "oidc":
		fallthrough
	case "google":
		fallthrough
	case "github":
		fallthrough
	case "microsoft":
		*e = AuthenticationProviderDataMicrosoftIDPConfigType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AuthenticationProviderDataMicrosoftIDPConfigType: %v", v)
	}
}

type AuthenticationProviderDataMicrosoftIDPConfigConfig struct {
	// Tenant ID for Microsoft authentication
	Tenant *string `default:"common" json:"tenant"`
}

func (a AuthenticationProviderDataMicrosoftIDPConfigConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthenticationProviderDataMicrosoftIDPConfigConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuthenticationProviderDataMicrosoftIDPConfigConfig) GetTenant() *string {
	if a == nil {
		return nil
	}
	return a.Tenant
}

type AuthenticationProviderDataMicrosoftIDPConfig struct {
	// Type of the authentication provider
	Type AuthenticationProviderDataMicrosoftIDPConfigType `json:"type"`
	// Name of the authentication provider
	Name string `json:"name"`
	// Client ID for the authentication provider
	ClientID string `json:"clientID"`
	// Client secret for the authentication provider
	ClientSecret string                                             `json:"clientSecret"`
	Config       AuthenticationProviderDataMicrosoftIDPConfigConfig `json:"config"`
}

func (a AuthenticationProviderDataMicrosoftIDPConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthenticationProviderDataMicrosoftIDPConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuthenticationProviderDataMicrosoftIDPConfig) GetType() AuthenticationProviderDataMicrosoftIDPConfigType {
	if a == nil {
		return AuthenticationProviderDataMicrosoftIDPConfigType("")
	}
	return a.Type
}

func (a *AuthenticationProviderDataMicrosoftIDPConfig) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AuthenticationProviderDataMicrosoftIDPConfig) GetClientID() string {
	if a == nil {
		return ""
	}
	return a.ClientID
}

func (a *AuthenticationProviderDataMicrosoftIDPConfig) GetClientSecret() string {
	if a == nil {
		return ""
	}
	return a.ClientSecret
}

func (a *AuthenticationProviderDataMicrosoftIDPConfig) GetConfig() AuthenticationProviderDataMicrosoftIDPConfigConfig {
	if a == nil {
		return AuthenticationProviderDataMicrosoftIDPConfigConfig{}
	}
	return a.Config
}

// AuthenticationProviderDataGoogleIDPConfigType - Type of the authentication provider
type AuthenticationProviderDataGoogleIDPConfigType string

const (
	AuthenticationProviderDataGoogleIDPConfigTypeOidc      AuthenticationProviderDataGoogleIDPConfigType = "oidc"
	AuthenticationProviderDataGoogleIDPConfigTypeGoogle    AuthenticationProviderDataGoogleIDPConfigType = "google"
	AuthenticationProviderDataGoogleIDPConfigTypeGithub    AuthenticationProviderDataGoogleIDPConfigType = "github"
	AuthenticationProviderDataGoogleIDPConfigTypeMicrosoft AuthenticationProviderDataGoogleIDPConfigType = "microsoft"
)

func (e AuthenticationProviderDataGoogleIDPConfigType) ToPointer() *AuthenticationProviderDataGoogleIDPConfigType {
	return &e
}
func (e *AuthenticationProviderDataGoogleIDPConfigType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "oidc":
		fallthrough
	case "google":
		fallthrough
	case "github":
		fallthrough
	case "microsoft":
		*e = AuthenticationProviderDataGoogleIDPConfigType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AuthenticationProviderDataGoogleIDPConfigType: %v", v)
	}
}

type AuthenticationProviderDataGoogleIDPConfigConfig struct {
}

func (a AuthenticationProviderDataGoogleIDPConfigConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthenticationProviderDataGoogleIDPConfigConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

type AuthenticationProviderDataGoogleIDPConfig struct {
	// Type of the authentication provider
	Type AuthenticationProviderDataGoogleIDPConfigType `json:"type"`
	// Name of the authentication provider
	Name string `json:"name"`
	// Client ID for the authentication provider
	ClientID string `json:"clientID"`
	// Client secret for the authentication provider
	ClientSecret string                                          `json:"clientSecret"`
	Config       AuthenticationProviderDataGoogleIDPConfigConfig `json:"config"`
}

func (a AuthenticationProviderDataGoogleIDPConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthenticationProviderDataGoogleIDPConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuthenticationProviderDataGoogleIDPConfig) GetType() AuthenticationProviderDataGoogleIDPConfigType {
	if a == nil {
		return AuthenticationProviderDataGoogleIDPConfigType("")
	}
	return a.Type
}

func (a *AuthenticationProviderDataGoogleIDPConfig) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AuthenticationProviderDataGoogleIDPConfig) GetClientID() string {
	if a == nil {
		return ""
	}
	return a.ClientID
}

func (a *AuthenticationProviderDataGoogleIDPConfig) GetClientSecret() string {
	if a == nil {
		return ""
	}
	return a.ClientSecret
}

func (a *AuthenticationProviderDataGoogleIDPConfig) GetConfig() AuthenticationProviderDataGoogleIDPConfigConfig {
	if a == nil {
		return AuthenticationProviderDataGoogleIDPConfigConfig{}
	}
	return a.Config
}

type AuthenticationProviderDataType string

const (
	AuthenticationProviderDataTypeAuthenticationProviderDataGoogleIDPConfig    AuthenticationProviderDataType = "AuthenticationProviderData_GoogleIDPConfig"
	AuthenticationProviderDataTypeAuthenticationProviderDataMicrosoftIDPConfig AuthenticationProviderDataType = "AuthenticationProviderData_MicrosoftIDPConfig"
	AuthenticationProviderDataTypeAuthenticationProviderDataGithubIDPConfig    AuthenticationProviderDataType = "AuthenticationProviderData_GithubIDPConfig"
	AuthenticationProviderDataTypeAuthenticationProviderDataOIDCConfig         AuthenticationProviderDataType = "AuthenticationProviderData_OIDCConfig"
)

type AuthenticationProviderData struct {
	AuthenticationProviderDataGoogleIDPConfig    *AuthenticationProviderDataGoogleIDPConfig    `queryParam:"inline,name=AuthenticationProviderData" union:"member"`
	AuthenticationProviderDataMicrosoftIDPConfig *AuthenticationProviderDataMicrosoftIDPConfig `queryParam:"inline,name=AuthenticationProviderData" union:"member"`
	AuthenticationProviderDataGithubIDPConfig    *AuthenticationProviderDataGithubIDPConfig    `queryParam:"inline,name=AuthenticationProviderData" union:"member"`
	AuthenticationProviderDataOIDCConfig         *AuthenticationProviderDataOIDCConfig         `queryParam:"inline,name=AuthenticationProviderData" union:"member"`

	Type AuthenticationProviderDataType
}

func CreateAuthenticationProviderDataAuthenticationProviderDataGoogleIDPConfig(authenticationProviderDataGoogleIDPConfig AuthenticationProviderDataGoogleIDPConfig) AuthenticationProviderData {
	typ := AuthenticationProviderDataTypeAuthenticationProviderDataGoogleIDPConfig

	return AuthenticationProviderData{
		AuthenticationProviderDataGoogleIDPConfig: &authenticationProviderDataGoogleIDPConfig,
		Type: typ,
	}
}

func CreateAuthenticationProviderDataAuthenticationProviderDataMicrosoftIDPConfig(authenticationProviderDataMicrosoftIDPConfig AuthenticationProviderDataMicrosoftIDPConfig) AuthenticationProviderData {
	typ := AuthenticationProviderDataTypeAuthenticationProviderDataMicrosoftIDPConfig

	return AuthenticationProviderData{
		AuthenticationProviderDataMicrosoftIDPConfig: &authenticationProviderDataMicrosoftIDPConfig,
		Type: typ,
	}
}

func CreateAuthenticationProviderDataAuthenticationProviderDataGithubIDPConfig(authenticationProviderDataGithubIDPConfig AuthenticationProviderDataGithubIDPConfig) AuthenticationProviderData {
	typ := AuthenticationProviderDataTypeAuthenticationProviderDataGithubIDPConfig

	return AuthenticationProviderData{
		AuthenticationProviderDataGithubIDPConfig: &authenticationProviderDataGithubIDPConfig,
		Type: typ,
	}
}

func CreateAuthenticationProviderDataAuthenticationProviderDataOIDCConfig(authenticationProviderDataOIDCConfig AuthenticationProviderDataOIDCConfig) AuthenticationProviderData {
	typ := AuthenticationProviderDataTypeAuthenticationProviderDataOIDCConfig

	return AuthenticationProviderData{
		AuthenticationProviderDataOIDCConfig: &authenticationProviderDataOIDCConfig,
		Type:                                 typ,
	}
}

func (u *AuthenticationProviderData) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var authenticationProviderDataGoogleIDPConfig AuthenticationProviderDataGoogleIDPConfig = AuthenticationProviderDataGoogleIDPConfig{}
	if err := utils.UnmarshalJSON(data, &authenticationProviderDataGoogleIDPConfig, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  AuthenticationProviderDataTypeAuthenticationProviderDataGoogleIDPConfig,
			Value: &authenticationProviderDataGoogleIDPConfig,
		})
	}

	var authenticationProviderDataMicrosoftIDPConfig AuthenticationProviderDataMicrosoftIDPConfig = AuthenticationProviderDataMicrosoftIDPConfig{}
	if err := utils.UnmarshalJSON(data, &authenticationProviderDataMicrosoftIDPConfig, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  AuthenticationProviderDataTypeAuthenticationProviderDataMicrosoftIDPConfig,
			Value: &authenticationProviderDataMicrosoftIDPConfig,
		})
	}

	var authenticationProviderDataGithubIDPConfig AuthenticationProviderDataGithubIDPConfig = AuthenticationProviderDataGithubIDPConfig{}
	if err := utils.UnmarshalJSON(data, &authenticationProviderDataGithubIDPConfig, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  AuthenticationProviderDataTypeAuthenticationProviderDataGithubIDPConfig,
			Value: &authenticationProviderDataGithubIDPConfig,
		})
	}

	var authenticationProviderDataOIDCConfig AuthenticationProviderDataOIDCConfig = AuthenticationProviderDataOIDCConfig{}
	if err := utils.UnmarshalJSON(data, &authenticationProviderDataOIDCConfig, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  AuthenticationProviderDataTypeAuthenticationProviderDataOIDCConfig,
			Value: &authenticationProviderDataOIDCConfig,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for AuthenticationProviderData", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for AuthenticationProviderData", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(AuthenticationProviderDataType)
	switch best.Type {
	case AuthenticationProviderDataTypeAuthenticationProviderDataGoogleIDPConfig:
		u.AuthenticationProviderDataGoogleIDPConfig = best.Value.(*AuthenticationProviderDataGoogleIDPConfig)
		return nil
	case AuthenticationProviderDataTypeAuthenticationProviderDataMicrosoftIDPConfig:
		u.AuthenticationProviderDataMicrosoftIDPConfig = best.Value.(*AuthenticationProviderDataMicrosoftIDPConfig)
		return nil
	case AuthenticationProviderDataTypeAuthenticationProviderDataGithubIDPConfig:
		u.AuthenticationProviderDataGithubIDPConfig = best.Value.(*AuthenticationProviderDataGithubIDPConfig)
		return nil
	case AuthenticationProviderDataTypeAuthenticationProviderDataOIDCConfig:
		u.AuthenticationProviderDataOIDCConfig = best.Value.(*AuthenticationProviderDataOIDCConfig)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for AuthenticationProviderData", string(data))
}

func (u AuthenticationProviderData) MarshalJSON() ([]byte, error) {
	if u.AuthenticationProviderDataGoogleIDPConfig != nil {
		return utils.MarshalJSON(u.AuthenticationProviderDataGoogleIDPConfig, "", true)
	}

	if u.AuthenticationProviderDataMicrosoftIDPConfig != nil {
		return utils.MarshalJSON(u.AuthenticationProviderDataMicrosoftIDPConfig, "", true)
	}

	if u.AuthenticationProviderDataGithubIDPConfig != nil {
		return utils.MarshalJSON(u.AuthenticationProviderDataGithubIDPConfig, "", true)
	}

	if u.AuthenticationProviderDataOIDCConfig != nil {
		return utils.MarshalJSON(u.AuthenticationProviderDataOIDCConfig, "", true)
	}

	return nil, errors.New("could not marshal union type AuthenticationProviderData: all fields are null")
}
