// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type Capability string

const (
	CapabilityModuleSelection Capability = "MODULE_SELECTION"
)

func (e Capability) ToPointer() *Capability {
	return &e
}
func (e *Capability) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "MODULE_SELECTION":
		*e = Capability(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Capability: %v", v)
	}
}
