// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreatePolicyRequest struct {
	// Policy name
	Name string `json:"name"`
	// Policy description
	Description *string `json:"description,omitzero"`
}

func (c *CreatePolicyRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreatePolicyRequest) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}
