// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/fctl/v3/internal/membershipclient/internal/utils"
)

type CreateUserResponse struct {
	Data *User `json:"data,omitzero"`
}

func (c CreateUserResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateUserResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateUserResponse) GetData() *User {
	if c == nil {
		return nil
	}
	return c.Data
}
