// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/fctl/internal/membershipclient/v3/internal/utils"
)

type CreateOrganizationResponse struct {
	Data *OrganizationExpanded `json:"data,omitzero"`
}

func (c CreateOrganizationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateOrganizationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateOrganizationResponse) GetData() *OrganizationExpanded {
	if c == nil {
		return nil
	}
	return c.Data
}
