// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/fctl/internal/membershipclient/internal/utils"
)

type CreateStackRequest struct {
	// Stack name
	Name     string            `json:"name"`
	Metadata map[string]string `json:"metadata,omitzero"`
	// Supported only with agent version >= v0.7.0
	Version  *string `json:"version,omitzero"`
	RegionID string  `json:"regionID"`
}

func (c CreateStackRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateStackRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"name", "regionID"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateStackRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateStackRequest) GetMetadata() map[string]string {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CreateStackRequest) GetVersion() *string {
	if c == nil {
		return nil
	}
	return c.Version
}

func (c *CreateStackRequest) GetRegionID() string {
	if c == nil {
		return ""
	}
	return c.RegionID
}
