// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreatePrivateRegionRequest struct {
	Name string `json:"name"`
}

func (c *CreatePrivateRegionRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}
