// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/fctl/internal/membershipclient/internal/utils"
)

type CreateInvitationResponse struct {
	Data *Invitation `json:"data,omitzero"`
}

func (c CreateInvitationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateInvitationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateInvitationResponse) GetData() *Invitation {
	if c == nil {
		return nil
	}
	return c.Data
}
