// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateApplicationClientResponse struct {
	Data ApplicationClient `json:"data"`
}

func (c *CreateApplicationClientResponse) GetData() ApplicationClient {
	if c == nil {
		return ApplicationClient{}
	}
	return c.Data
}
