// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/fctl/internal/membershipclient/internal/utils"
)

type CreateApplicationResponse struct {
	Data *Application `json:"data,omitzero"`
}

func (c CreateApplicationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateApplicationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateApplicationResponse) GetData() *Application {
	if c == nil {
		return nil
	}
	return c.Data
}
