// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/fctl/internal/membershipclient/v3/internal/utils"
)

type EnableApplicationForOrganizationResponse struct {
	Data *OrganizationApplication `json:"data,omitzero"`
}

func (e EnableApplicationForOrganizationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EnableApplicationForOrganizationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EnableApplicationForOrganizationResponse) GetData() *OrganizationApplication {
	if e == nil {
		return nil
	}
	return e.Data
}
