// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Error struct {
	ErrorCode    string  `json:"errorCode"`
	ErrorMessage *string `json:"errorMessage,omitzero"`
}

func (e *Error) GetErrorCode() string {
	if e == nil {
		return ""
	}
	return e.ErrorCode
}

func (e *Error) GetErrorMessage() *string {
	if e == nil {
		return nil
	}
	return e.ErrorMessage
}
