// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetRegionVersionsResponse struct {
	Data []Version `json:"data"`
}

func (g *GetRegionVersionsResponse) GetData() []Version {
	if g == nil {
		return []Version{}
	}
	return g.Data
}
