// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/fctl/internal/membershipclient/internal/utils"
)

type ListInvitationsResponse struct {
	Data []Invitation `json:"data,omitzero"`
}

func (l ListInvitationsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListInvitationsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListInvitationsResponse) GetData() []Invitation {
	if l == nil {
		return nil
	}
	return l.Data
}
