// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/formancehq/fctl/internal/membershipclient/internal/utils"
	"time"
)

type ModuleState string

const (
	ModuleStateEnabled  ModuleState = "ENABLED"
	ModuleStateDisabled ModuleState = "DISABLED"
)

func (e ModuleState) ToPointer() *ModuleState {
	return &e
}
func (e *ModuleState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ENABLED":
		fallthrough
	case "DISABLED":
		*e = ModuleState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ModuleState: %v", v)
	}
}

type ModuleStatus string

const (
	ModuleStatusUnknown     ModuleStatus = "UNKNOWN"
	ModuleStatusProgressing ModuleStatus = "PROGRESSING"
	ModuleStatusReady       ModuleStatus = "READY"
	ModuleStatusDeleted     ModuleStatus = "DELETED"
)

func (e ModuleStatus) ToPointer() *ModuleStatus {
	return &e
}
func (e *ModuleStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "UNKNOWN":
		fallthrough
	case "PROGRESSING":
		fallthrough
	case "READY":
		fallthrough
	case "DELETED":
		*e = ModuleStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ModuleStatus: %v", v)
	}
}

type ClusterStatus struct {
}

type Module struct {
	Name             string         `json:"name"`
	State            ModuleState    `json:"state"`
	Status           ModuleStatus   `json:"status"`
	LastStatusUpdate time.Time      `json:"lastStatusUpdate"`
	LastStateUpdate  time.Time      `json:"lastStateUpdate"`
	ClusterStatus    *ClusterStatus `json:"clusterStatus,omitzero"`
}

func (m Module) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *Module) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, []string{"name", "state", "status", "lastStatusUpdate", "lastStateUpdate"}); err != nil {
		return err
	}
	return nil
}

func (m *Module) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}

func (m *Module) GetState() ModuleState {
	if m == nil {
		return ModuleState("")
	}
	return m.State
}

func (m *Module) GetStatus() ModuleStatus {
	if m == nil {
		return ModuleStatus("")
	}
	return m.Status
}

func (m *Module) GetLastStatusUpdate() time.Time {
	if m == nil {
		return time.Time{}
	}
	return m.LastStatusUpdate
}

func (m *Module) GetLastStateUpdate() time.Time {
	if m == nil {
		return time.Time{}
	}
	return m.LastStateUpdate
}

func (m *Module) GetClusterStatus() *ClusterStatus {
	if m == nil {
		return nil
	}
	return m.ClusterStatus
}
