// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/fctl/internal/membershipclient/internal/utils"
	"time"
)

type ModuleState string

const (
	ModuleStateEnabled  ModuleState = "ENABLED"
	ModuleStateDisabled ModuleState = "DISABLED"
)

func (e ModuleState) ToPointer() *ModuleState {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ModuleState) IsExact() bool {
	if e != nil {
		switch *e {
		case "ENABLED", "DISABLED":
			return true
		}
	}
	return false
}

type ModuleStatus string

const (
	ModuleStatusUnknown     ModuleStatus = "UNKNOWN"
	ModuleStatusProgressing ModuleStatus = "PROGRESSING"
	ModuleStatusReady       ModuleStatus = "READY"
	ModuleStatusDeleted     ModuleStatus = "DELETED"
)

func (e ModuleStatus) ToPointer() *ModuleStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ModuleStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "UNKNOWN", "PROGRESSING", "READY", "DELETED":
			return true
		}
	}
	return false
}

type ClusterStatus struct {
}

type Module struct {
	Name             string         `json:"name"`
	State            ModuleState    `json:"state"`
	Status           ModuleStatus   `json:"status"`
	LastStatusUpdate time.Time      `json:"lastStatusUpdate"`
	LastStateUpdate  time.Time      `json:"lastStateUpdate"`
	ClusterStatus    *ClusterStatus `json:"clusterStatus,omitzero"`
}

func (m Module) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *Module) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *Module) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}

func (m *Module) GetState() ModuleState {
	if m == nil {
		return ModuleState("")
	}
	return m.State
}

func (m *Module) GetStatus() ModuleStatus {
	if m == nil {
		return ModuleStatus("")
	}
	return m.Status
}

func (m *Module) GetLastStatusUpdate() time.Time {
	if m == nil {
		return time.Time{}
	}
	return m.LastStatusUpdate
}

func (m *Module) GetLastStateUpdate() time.Time {
	if m == nil {
		return time.Time{}
	}
	return m.LastStateUpdate
}

func (m *Module) GetClusterStatus() *ClusterStatus {
	if m == nil {
		return nil
	}
	return m.ClusterStatus
}
