// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/fctl/v3/internal/membershipclient/internal/utils"
	"time"
)

type OrganizationExpanded struct {
	// Organization name
	Name string `json:"name"`
	// Organization domain
	Domain *string `json:"domain,omitzero"`
	// Default policy ID applied to new users
	DefaultPolicyID *int64 `json:"defaultPolicyID"`
	// Organization ID
	ID string `json:"id"`
	// Owner ID
	OwnerID string `json:"ownerId"`
	// Number of available stacks
	AvailableStacks *int64 `json:"availableStacks,omitzero"`
	// Number of available sandboxes
	AvailableSandboxes *int64     `json:"availableSandboxes,omitzero"`
	CreatedAt          *time.Time `json:"createdAt,omitzero"`
	UpdatedAt          *time.Time `json:"updatedAt,omitzero"`
	TotalStacks        *int64     `json:"totalStacks,omitzero"`
	TotalUsers         *int64     `json:"totalUsers,omitzero"`
	Owner              *User      `json:"owner,omitzero"`
}

func (o OrganizationExpanded) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationExpanded) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationExpanded) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *OrganizationExpanded) GetDomain() *string {
	if o == nil {
		return nil
	}
	return o.Domain
}

func (o *OrganizationExpanded) GetDefaultPolicyID() *int64 {
	if o == nil {
		return nil
	}
	return o.DefaultPolicyID
}

func (o *OrganizationExpanded) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *OrganizationExpanded) GetOwnerID() string {
	if o == nil {
		return ""
	}
	return o.OwnerID
}

func (o *OrganizationExpanded) GetAvailableStacks() *int64 {
	if o == nil {
		return nil
	}
	return o.AvailableStacks
}

func (o *OrganizationExpanded) GetAvailableSandboxes() *int64 {
	if o == nil {
		return nil
	}
	return o.AvailableSandboxes
}

func (o *OrganizationExpanded) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *OrganizationExpanded) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}

func (o *OrganizationExpanded) GetTotalStacks() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalStacks
}

func (o *OrganizationExpanded) GetTotalUsers() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalUsers
}

func (o *OrganizationExpanded) GetOwner() *User {
	if o == nil {
		return nil
	}
	return o.Owner
}
