// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PolicyData struct {
	// Policy name
	Name string `json:"name"`
	// Policy description
	Description *string `json:"description,omitzero"`
}

func (p *PolicyData) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PolicyData) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}
