// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/fctl/v3/internal/membershipclient/internal/utils"
	"time"
)

type PrivateRegion struct {
	ID             string               `json:"id"`
	BaseURL        string               `json:"baseUrl"`
	CreatedAt      string               `json:"createdAt"`
	Active         bool                 `json:"active"`
	LastPing       *time.Time           `json:"lastPing,omitzero"`
	Name           string               `json:"name"`
	Capabilities   RegionCapability     `json:"capabilities"`
	AgentID        string               `json:"agentID"`
	Outdated       bool                 `json:"outdated"`
	CreatorID      *string              `json:"creatorId,omitzero"`
	Version        *string              `json:"version,omitzero"`
	OrganizationID string               `json:"organizationID"`
	CreatorId1     string               `json:"creatorID"`
	Secret         *PrivateRegionSecret `json:"secret,omitzero"`
}

func (p PrivateRegion) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PrivateRegion) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PrivateRegion) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PrivateRegion) GetBaseURL() string {
	if p == nil {
		return ""
	}
	return p.BaseURL
}

func (p *PrivateRegion) GetCreatedAt() string {
	if p == nil {
		return ""
	}
	return p.CreatedAt
}

func (p *PrivateRegion) GetActive() bool {
	if p == nil {
		return false
	}
	return p.Active
}

func (p *PrivateRegion) GetLastPing() *time.Time {
	if p == nil {
		return nil
	}
	return p.LastPing
}

func (p *PrivateRegion) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PrivateRegion) GetCapabilities() RegionCapability {
	if p == nil {
		return RegionCapability{}
	}
	return p.Capabilities
}

func (p *PrivateRegion) GetAgentID() string {
	if p == nil {
		return ""
	}
	return p.AgentID
}

func (p *PrivateRegion) GetOutdated() bool {
	if p == nil {
		return false
	}
	return p.Outdated
}

func (p *PrivateRegion) GetCreatorID() *string {
	if p == nil {
		return nil
	}
	return p.CreatorID
}

func (p *PrivateRegion) GetVersion() *string {
	if p == nil {
		return nil
	}
	return p.Version
}

func (p *PrivateRegion) GetOrganizationID() string {
	if p == nil {
		return ""
	}
	return p.OrganizationID
}

func (p *PrivateRegion) GetCreatorId1() string {
	if p == nil {
		return ""
	}
	return p.CreatorId1
}

func (p *PrivateRegion) GetSecret() *PrivateRegionSecret {
	if p == nil {
		return nil
	}
	return p.Secret
}
