// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ReadOrganizationClientsResponseData struct {
	PageSize int64                `json:"pageSize"`
	HasMore  bool                 `json:"hasMore"`
	Previous *string              `json:"previous,omitzero"`
	Next     *string              `json:"next,omitzero"`
	Data     []OrganizationClient `json:"data"`
}

func (r *ReadOrganizationClientsResponseData) GetPageSize() int64 {
	if r == nil {
		return 0
	}
	return r.PageSize
}

func (r *ReadOrganizationClientsResponseData) GetHasMore() bool {
	if r == nil {
		return false
	}
	return r.HasMore
}

func (r *ReadOrganizationClientsResponseData) GetPrevious() *string {
	if r == nil {
		return nil
	}
	return r.Previous
}

func (r *ReadOrganizationClientsResponseData) GetNext() *string {
	if r == nil {
		return nil
	}
	return r.Next
}

func (r *ReadOrganizationClientsResponseData) GetData() []OrganizationClient {
	if r == nil {
		return []OrganizationClient{}
	}
	return r.Data
}

type ReadOrganizationClientsResponse struct {
	Data ReadOrganizationClientsResponseData `json:"data"`
}

func (r *ReadOrganizationClientsResponse) GetData() ReadOrganizationClientsResponseData {
	if r == nil {
		return ReadOrganizationClientsResponseData{}
	}
	return r.Data
}
