// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/fctl/internal/membershipclient/v3/internal/utils"
)

type ReadUserResponse struct {
	Data *User `json:"data,omitzero"`
}

func (r ReadUserResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReadUserResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReadUserResponse) GetData() *User {
	if r == nil {
		return nil
	}
	return r.Data
}
