// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/fctl/internal/membershipclient/internal/utils"
	"github.com/formancehq/fctl/internal/membershipclient/optionalnullable"
)

type ReadStackUserAccessData struct {
	// Stack ID
	StackID string `json:"stackId"`
	// User ID
	UserID string `json:"userId"`
	// User email
	Email string `json:"email"`
	// Policy ID applied to the user for the stack
	PolicyID int64 `json:"policyId"`
	// Policy ID applied to the user at the organization level
	OrganizationPolicyID optionalnullable.OptionalNullable[int64] `json:"organizationPolicyId,omitzero"`
}

func (r *ReadStackUserAccessData) GetStackID() string {
	if r == nil {
		return ""
	}
	return r.StackID
}

func (r *ReadStackUserAccessData) GetUserID() string {
	if r == nil {
		return ""
	}
	return r.UserID
}

func (r *ReadStackUserAccessData) GetEmail() string {
	if r == nil {
		return ""
	}
	return r.Email
}

func (r *ReadStackUserAccessData) GetPolicyID() int64 {
	if r == nil {
		return 0
	}
	return r.PolicyID
}

func (r *ReadStackUserAccessData) GetOrganizationPolicyID() optionalnullable.OptionalNullable[int64] {
	if r == nil {
		return nil
	}
	return r.OrganizationPolicyID
}

type ReadStackUserAccess struct {
	Data *ReadStackUserAccessData `json:"data,omitzero"`
}

func (r ReadStackUserAccess) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReadStackUserAccess) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReadStackUserAccess) GetData() *ReadStackUserAccessData {
	if r == nil {
		return nil
	}
	return r.Data
}
