// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/fctl/v3/internal/membershipclient/internal/utils"
)

type ReadOrganizationUserResponseData struct {
	Email string `json:"email"`
	ID    string `json:"id"`
	// Policy ID applied to the user
	PolicyID int64 `json:"policyId"`
}

func (r *ReadOrganizationUserResponseData) GetEmail() string {
	if r == nil {
		return ""
	}
	return r.Email
}

func (r *ReadOrganizationUserResponseData) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *ReadOrganizationUserResponseData) GetPolicyID() int64 {
	if r == nil {
		return 0
	}
	return r.PolicyID
}

type ReadOrganizationUserResponse struct {
	Data *ReadOrganizationUserResponseData `json:"data,omitzero"`
}

func (r ReadOrganizationUserResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReadOrganizationUserResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReadOrganizationUserResponse) GetData() *ReadOrganizationUserResponseData {
	if r == nil {
		return nil
	}
	return r.Data
}
