// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/fctl/v3/internal/membershipclient/internal/utils"
)

type ReadPolicyResponse struct {
	Data *Policy `json:"data,omitzero"`
}

func (r ReadPolicyResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReadPolicyResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReadPolicyResponse) GetData() *Policy {
	if r == nil {
		return nil
	}
	return r.Data
}
