// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/fctl/internal/membershipclient/internal/utils"
	"time"
)

type Region struct {
	ID           string           `json:"id"`
	BaseURL      string           `json:"baseUrl"`
	CreatedAt    string           `json:"createdAt"`
	Active       bool             `json:"active"`
	LastPing     *time.Time       `json:"lastPing,omitzero"`
	Name         string           `json:"name"`
	Capabilities RegionCapability `json:"capabilities"`
	AgentID      string           `json:"agentID"`
	Outdated     bool             `json:"outdated"`
	CreatorID    *string          `json:"creatorId,omitzero"`
	Version      *string          `json:"version,omitzero"`
}

func (r Region) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *Region) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"id", "baseUrl", "createdAt", "active", "name", "capabilities", "agentID", "outdated"}); err != nil {
		return err
	}
	return nil
}

func (r *Region) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *Region) GetBaseURL() string {
	if r == nil {
		return ""
	}
	return r.BaseURL
}

func (r *Region) GetCreatedAt() string {
	if r == nil {
		return ""
	}
	return r.CreatedAt
}

func (r *Region) GetActive() bool {
	if r == nil {
		return false
	}
	return r.Active
}

func (r *Region) GetLastPing() *time.Time {
	if r == nil {
		return nil
	}
	return r.LastPing
}

func (r *Region) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *Region) GetCapabilities() RegionCapability {
	if r == nil {
		return RegionCapability{}
	}
	return r.Capabilities
}

func (r *Region) GetAgentID() string {
	if r == nil {
		return ""
	}
	return r.AgentID
}

func (r *Region) GetOutdated() bool {
	if r == nil {
		return false
	}
	return r.Outdated
}

func (r *Region) GetCreatorID() *string {
	if r == nil {
		return nil
	}
	return r.CreatorID
}

func (r *Region) GetVersion() *string {
	if r == nil {
		return nil
	}
	return r.Version
}
