// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/fctl/internal/membershipclient/v3/internal/utils"
)

type RegionCapability struct {
	ModuleList []string `json:"MODULE_LIST,omitzero"`
	Ee         []string `json:"EE,omitzero"`
}

func (r RegionCapability) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RegionCapability) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RegionCapability) GetModuleList() []string {
	if r == nil {
		return nil
	}
	return r.ModuleList
}

func (r *RegionCapability) GetEe() []string {
	if r == nil {
		return nil
	}
	return r.Ee
}
