// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/fctl/internal/membershipclient/internal/utils"
	"time"
)

type Scope struct {
	// Scope ID
	ID int64 `json:"id"`
	// The OAuth2 scope label (e.g., "custom:read")
	Label string `json:"label"`
	// Scope description
	Description *string `json:"description,omitzero"`
	// Application ID (null for global scopes)
	ApplicationID *string `json:"applicationId,omitzero"`
	// Whether the scope is protected
	Protected *bool `default:"false" json:"protected"`
	// Creation timestamp
	CreatedAt time.Time `json:"createdAt"`
	// Last update timestamp
	UpdatedAt time.Time `json:"updatedAt"`
}

func (s Scope) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Scope) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *Scope) GetID() int64 {
	if s == nil {
		return 0
	}
	return s.ID
}

func (s *Scope) GetLabel() string {
	if s == nil {
		return ""
	}
	return s.Label
}

func (s *Scope) GetDescription() *string {
	if s == nil {
		return nil
	}
	return s.Description
}

func (s *Scope) GetApplicationID() *string {
	if s == nil {
		return nil
	}
	return s.ApplicationID
}

func (s *Scope) GetProtected() *bool {
	if s == nil {
		return nil
	}
	return s.Protected
}

func (s *Scope) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}

func (s *Scope) GetUpdatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.UpdatedAt
}
