// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	Oauth2 string `security:"scheme,type=oauth2,name=Authorization"`
}

func (s *Security) GetOauth2() string {
	if s == nil {
		return ""
	}
	return s.Oauth2
}
