// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type StackVersion struct {
	// Supported only with agent version >= v0.7.0
	Version *string `json:"version,omitzero"`
}

func (s *StackVersion) GetVersion() *string {
	if s == nil {
		return nil
	}
	return s.Version
}
