// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/fctl/v3/internal/membershipclient/internal/utils"
)

type StackData struct {
	// Stack name
	Name     string            `json:"name"`
	Metadata map[string]string `json:"metadata,omitzero"`
}

func (s StackData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StackData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StackData) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *StackData) GetMetadata() map[string]string {
	if s == nil {
		return nil
	}
	return s.Metadata
}
