// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateApplicationClientRequest struct {
	// Name of the client
	Name string `json:"name"`
	// Description of the client
	Description *string `json:"description,omitzero"`
}

func (u *UpdateApplicationClientRequest) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}

func (u *UpdateApplicationClientRequest) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}
