// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/fctl/internal/membershipclient/internal/utils"
)

type UpdateApplicationResponse struct {
	Data *Application `json:"data,omitzero"`
}

func (u UpdateApplicationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateApplicationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateApplicationResponse) GetData() *Application {
	if u == nil {
		return nil
	}
	return u.Data
}
