// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type User struct {
	Email string `json:"email"`
	// User ID
	ID   string      `json:"id"`
	Role *SystemRole `json:"role,omitzero"`
}

func (u *User) GetEmail() string {
	if u == nil {
		return ""
	}
	return u.Email
}

func (u *User) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *User) GetRole() *SystemRole {
	if u == nil {
		return nil
	}
	return u.Role
}
