// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Version struct {
	Name     string            `json:"name"`
	Versions map[string]string `json:"versions"`
	RegionID string            `json:"regionID"`
}

func (v *Version) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *Version) GetVersions() map[string]string {
	if v == nil {
		return map[string]string{}
	}
	return v.Versions
}

func (v *Version) GetRegionID() string {
	if v == nil {
		return ""
	}
	return v.RegionID
}
